### ISSUE TITLE
Playlist Title, Artist Name, Genre Name are empty in List View

### ISSUE THREAD

**Issue by IceWreck** [jeffvli/sonixd#104]
**To Reproduce**
1. Click on Artists in the sidebar. Alternatively click on the Playlist view.

**Expected behavior**
I expect to see the playlist title in list view. And the artist name and so on...

**Screenshots**

**Describe the bug**
![image](https://user-images.githubusercontent.com/18102790/143451124-7f388317-efa5-45b4-a388-f993cb30df93.png)

All playlist titles are empty in list view. It works fine when I open up any specific playlist.

![image](https://user-images.githubusercontent.com/18102790/143451232-62d1438f-6b51-4dd3-a771-8e9f8703c569.png)
Same thing for Artist Name in Artists list view.

**Desktop (please complete the following information):**
 - OS: Fedora 34
 - Version 0.8.3, latest, just downloaded. Default settings.
 - Navidrome. (Latest version)

**Additional context**
It works in grid view. The problem is with list view only.

**Comment by jeffvli** [comment]
With the new update you'll have to remove and re-add the title column in the list-view column selectors. I made some changes to the data fields so the existing `Title` is now blank.

**Comment by IceWreck** [comment]
Thanks. Doing that fixed it. But FYI, 0.8.3 was the first version I tried and it was broken out of the box. I just discovered your client today after reading your (are you flameling on Discord ?) conversation with @deluan on the navidrome discord.

sonixd excellent btw, thank you.

**Comment by jeffvli** [comment]
Ugh.. thanks for that info. I forgot to update the default columns.

**Comment by jeffvli** [comment]
Closing since it's fixed in the latest version.
