### ISSUE TITLE
Gnome Media Bar issues

### ISSUE THREAD

**Issue by IceWreck** [jeffvli/sonixd#105]
**Describe the bug**
SonixD has multiple issues with Gnome Media Controls:

- Icon doesnt change on play/pause. It shows the same icon even when I pause music. This happens when I pause from the gnome media controls or from sonixd. However, if I play/pause music using my bluetooth headphones, then it does change the icon.
- It always says unknown artist the media controls. 
- There is no album art in the title bar.

**To Reproduce**
1. Play some music
2. Look at gnome music/media bar in the panel

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/18102790/143452579-e24afaba-8d91-49dc-8d74-789b554f5a4d.png)

**Desktop (please complete the following information):**
 - OS: Fedora 34
 - Version 0.8.3, latest, just downloaded. Default settings.
 - Navidrome. (Latest version)

**Comment by bwat47** [comment]
The icon not changing on play/pause also effects the playback controls on the windows OS taskbar thumbnail

**Comment by jeffvli** [comment]
I confirmed your findings and fixed it for Gnome (which uses the MPRIS standard).

 I'm not seeing any issues with the Windows 10 taskbar thumbnail though. Windows 10 doesn't dynamically update the window contents when the app is minimized so that was changed to the static window panel in an earlier issue when minimized #73.

**Comment by jeffvli** [comment]
Actually @bwat47, MPRIS lets us pass the actual image URL to it so we can dynamically change that on the fly, unlike what happens in Windows 10 as you found on #73.

**Comment by IceWreck** [comment]
Thank you. Will try the new version first thing tomorrow.

**Comment by bwat47** [comment]
@jeffvli sorry, to clarify I was referring to the play icon not changing to the pause icon rather than the thumbnail image itself

**Comment by jeffvli** [comment]
@bwat47 Ah got it. That's actually intended since I didn't add an extra image for the 'pause' event. I'll open a separate issue and see if I can add a pause button for that.
