### ISSUE TITLE
Album & Playlist Screen Adjustments (Jellyfin)

### ISSUE THREAD

**Issue by Vodes** [jeffvli/sonixd#110]
Would it be possible to make the album/playlist screen more similar to how it is in the jellyfin webinterface?

For example:

### Artist Placement in the Song List

It currently looks like
![](https://vodes.pw/i/Alex/myKqR6evcf9stXy.png)
But I would love it if it showed all the artists in that particular song there (like in the jellyfin webinterface)
![](https://vodes.pw/i/Alex/J3MJxTi4D4eIMGd.png)

### Artist & Genre Listing at the top of the page
If someone doesn't know what I'm talking about:
![](https://vodes.pw/i/Alex/JKEbfLCganN1LKO.png)

I think the Album Artist should be displayed differently from the others.
I'm thinking either make it a separate field or leave it in the same list but at the beginning (instead of having every artist alphabetically sorted) and with a separator afterwards.

I would also appreciate it if genres were in a separate list entirely. 
If you, for example, have a lot of artists in an album, I believe you should still be able to see the genres at a first glance.

Also please make those lists scrollable via mousewheel (if hovering on them)

Other than those small UI preferences I have, I'd say this is a great player so far and thank you a lot for your work ^^

**Comment by jeffvli** [comment]
Thanks for the great suggestions! The UI optimized for albums with a single artist and a single genre, back when the app only supported Subsonic so it can definitely be a wonky in a few places.

I'll add these changes for the next version.
