### ISSUE TITLE
Volume slider with a popup volume percentage on mouse over

### ISSUE THREAD

**Issue by JingAr87** [jeffvli/sonixd#112]
Coming from the Jellyfin web client, it would be really nice to have the same popup volume percentage card when mouse over the volume slider. And it would be great if you could also add volume control with the scroll wheel too.

**Comment by Zibbp** [comment]
I would love to see the ability to adjust the volume using your scrollbar while hovering over the volume bar.

**Comment by jeffvli** [comment]
I'll take a look into this for next release
