### ISSUE TITLE
Recently played not updating when playing through Sonixd

### ISSUE THREAD

**Issue by gobeye** [jeffvli/sonixd#114]
**Describe the bug**
Recently played is not updated when playing through Sonixd client. It updates fine when playing through any other client / web interface.

**To Reproduce**
Play an album in Sonixd.

**Expected behavior**
Recently played should update to show the last played album.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.8.5

**Comment by jeffvli** [comment]
What server are you running Sonixd on?

If you're on Navidrome, you'll need to tick the `Enable scrobbling` setting for it to send played tracks to your server.

**Comment by JingAr87** [comment]
I have the same issue with the server being Jellyfin.

**Comment by jeffvli** [comment]
@JingAr87 That's actually a bug on Jellyfin itself not properly returning albums. I saw an existing issue https://github.com/jellyfin/jellyfin/issues/2462 but it was never addressed or resolved. I'll probably open up a new issue to see if it can be fixed.

**Comment by gobeye** [comment]
> What server are you running Sonixd on?
> 
> If you're on Navidrome, you'll need to tick the `Enable scrobbling` setting for it to send played tracks to your server.

I am on Navidrome yes and can confirm that enabling scrobbling does correctly record the last played album.
