### ISSUE TITLE
Progress bar indicator can not be dragged from position other than progress indicator itself

### ISSUE THREAD

**Issue by luopa** [jeffvli/sonixd#120]
**Describe the bug**
When click-dragging into the progress bar, anywhere other than the progress indicator circle, progress bar doesnt work.

**To Reproduce**
1) Play a song. 
2) Click-hold-drag anywhere in the progress bar _other_ than the progress indicator circle itself.
3) No song scrolling occurs. Rather you are dragging the progress bar visual (or so).

**Expected behavior**
1) Play a song. 
2) Click-hold-drag anywhere in the progress bar _other_ than the progress indicator circle itself.
3) Progress indicator circle jumps to click position, moves around with drag and once released, song jumps to the respective position. 

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version: 0.8.5

**Kudos**
Thank you so much for this application - it's a gem already now! ❤️

**Comment by jeffvli** [comment]
The slider functionality is prebuilt from [rsuite's](https://v4.rsuitejs.com/components/slider/) so I'm not sure how easily I'll be able to modify it to drag from anywhere.

I'll do some testing on my side to see what I can do.

**Comment by luopa** [comment]
Oh ok,  I should rather report this there then. Sorry for bothering you here with it. Thanks anyway for looking into it 🙏
