### ISSUE TITLE
"Recently Played" filter does not work on Jellyfin

### ISSUE THREAD

**Issue by jeffvli** [jeffvli/sonixd#122]
**Describe the bug**
Recently played does not show the most recently played albums when using Jellyfin. This is a bug(?) on Jellyfin's side that does not return recently played albums from the API.

**To Reproduce**
1. View recently played on the dashboard or on the album list (using a filter
2. Albums are listed in default order

**Expected behavior**
Albums should be displayed by recently played.

**Additional context**
Looking at the native Jellyfin Web UI, recently played is only filterable by `Songs`, rather than `Albums`. Possibly implement a workaround by parsing songs and then referencing the song's parent album.

Alternatively, create an issue on Jellyfin repository asking for possible support of "Recently Played" albums feature.

**Comment by Maxplosion** [comment]
Just as an addition the same thing happens for "Most Played" on the Dashboard.
Both always show some default Album order which never changes. 
What works is Recently Added + Random (one of the best things btw!), those two work just fine.

**Comment by jeffvli** [comment]
I was taking a closer look at the Jellyfin API and I ran across [this issue](https://github.com/jellyfin/jellyfin/issues/2687). Since the `MusicAlbum` item types can't be marked as played (and thus are missing a last played date), and won't be fixed until the database migration is complete(?), I'll have to try adding the workaround.

**Comment by Maxplosion** [comment]
Would it be possbile to just apply this for songs here instead of MusicAlbum items? As for songs that works and is in use on the webclient already, so you might be able to use this approach for recently and most played.
Or is there some limitation in the code that requires it to use the full album for those too? (Applying to single items imo makes the most sense here)

**Comment by jeffvli** [comment]
I could do that for the dashboard, but it would be a little weird to have songs show up in the filtered "Album" list.

I'll look into adding a separate "Songs" tab since Jellyfin's API supports that.

**Comment by Maxplosion** [comment]
Oh now I understand, I was only thinking about the Dashboard view, did not even check the Album view (as it is not something I use, only use artist, genres and dashboard views most of the time)
