### ISSUE TITLE
[Jellyfin] Songs without embedded art do not have album art

### ISSUE THREAD

**Issue by jpdown** [jeffvli/sonixd#128]
**Describe the bug**
With Jellyfin, songs only have album art if the album art is embedded in the file. Albums use the cover.jpg from the folder but songs do not.

**To Reproduce**
1. Have a Jellyfin server with an album that has a cover.jpg in the folder and no embedded art.
2. View the album in Sonixd.
3. See that the album has the art but the songs do not.

**Expected behavior**
The songs should inherit the cover.jpg art from the folder.

**Screenshots**
An album with no embedded art in the files:
![image](https://user-images.githubusercontent.com/24631328/145689265-9fa530f4-9283-4ec4-8511-518af09ea19e.png)
An album with embedded art in the files:
![image](https://user-images.githubusercontent.com/24631328/145689285-bbecb267-bac3-419e-b9b3-542a0dc803dc.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: v0.9.1
 - Jellyfin Version: 10.7.7

**Additional context**
I have tested this with FLAC and MP3 files. Using a Navidrome server on the same files does not exhibit this issue.

**Comment by jeffvli** [comment]
Thanks, was able to confirm this on my side as well. I can have it fall back to the album art if no image is embedded.

A temporary workaround would be to turn on image caching which then populates your songs the with the album image (this is probably why I never noticed it sooner!).
