### ISSUE TITLE
Improve discoverability of song reordering

### ISSUE THREAD

**Issue by metronidazole** [jeffvli/sonixd#131]
**Is your feature request related to a problem? Please describe.**
It would be nice if it was possible to reorder songs in a playlist with drag and drop. Currently you can only do this by using a right click submenu which is suboptimal. 

**Describe the solution you'd like**
Should be able to use left click to drag a song (or multiple selected) to a new position in a playlist

**Describe alternatives you've considered**
Current implementation is suboptimal and slow for reordering multiple songs. 

**Additional context**
N/A

**Comment by jeffvli** [comment]
Playlist items can already be re-ordered by drag and drop (same as the Now Playing queue). You need to begin and end the drag operation from the `#` column like the [gif in the docs](https://github.com/jeffvli/sonixd/discussions/15).

**Comment by metronidazole** [comment]
Oh ok. That's not very accessible and I think most people would not find that. Maybe you could add a tooltip when reordering using the right click menu to improve discoverability?

**Comment by jeffvli** [comment]
Sure, I can add a tooltip there! I assumed most people would figure it out by the column names in the settings `# (Drag/Drop)`.
