### ISSUE TITLE
Jellyfin Playback Progress is not reported

### ISSUE THREAD

**Issue by maltechx** [jeffvli/sonixd#133]
**Describe the bug**
While playing a song in Sonixd the status of the playback is not reported back to Jellyfin.

**To Reproduce**
1. Play a Song in Sonixd
2. Log into Jellyfin and look at the Dashboard. You only see the client, but not that its actually playing anything.

**Expected behavior**
It should report the current playback progress and current music title.

**Screenshots**
How it should be:
![playback_progress](https://user-images.githubusercontent.com/47327545/145708879-4501e29f-ddad-45db-8062-2683fc5b2047.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: 0.9.1

**Additional context**

**Comment by jeffvli** [comment]
You need to tick the `Enable scrobbling` checkbox in the settings.

Note: there is a bug #126 in the current stable release with reported play counts if you turn it on.

**Comment by maltechx** [comment]
Thanks for the quick response. I've overlooked this option.
