### ISSUE TITLE
Funkwhale server not supported

### ISSUE THREAD

**Issue by jeffvli** [jeffvli/sonixd#135]
**Describe the bug**
Unable to sign into Sonixd using funkwhale[(?)](https://www.reddit.com/r/selfhosted/comments/re5wc2/sonixd_cross_platform_desktop_client_for_subsonic/ho6ap80/)

**To Reproduce**
1. Open Sonixd
2. Attempt to sign into to Funkwhale via Sonixd login page

**Expected behavior**
Signs into Sonixd and able to use the application

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ANY
 - Version: 0.9.1

**Comment by gelaechter** [comment]
For some reason Funkwhale doesn't handle some Subsonic API methods, in this case getScanStatus, which Sonixd uses to check if a hosts Subsonic API works.
![image](https://user-images.githubusercontent.com/30231932/145874851-24ae86e4-037f-4b4d-b98a-9af35437c34f.png)

This would actually be something to fix on funkwhales side rather than Sonixds, since funkwhale says its Subsonic REST API version is 1.16.0 which should handle these methods.

Response from ping method:
```xml
<subsonic-response funkwhaleVersion="1.1.4" status="ok" type="funkwhale" version="1.16.0"/>
```

**Comment by jeffvli** [comment]
@gelaechter Thanks for that info.

Seems like Funkwhale does [list its supported endpoints](https://docs.funkwhale.audio/developers/subsonic.html) and `getScanStatus` isn't part of it. If you have a funkwhale server setup, could you test if any parts of the application are broken with the existing endpoints?

**Comment by gelaechter** [comment]
@jeffvli 

That is exactly what i've been doing for the last hour or so. I forked sonixd and hacked a quick and dirty functioning version together and put it in a "funkwhale" branch. I added funkwhale as a third server type.

Whats not working:
- Scanning done in the config page
- The folders page

**Comment by gelaechter** [comment]
@jeffvli 

Hey, I just tested all endpoints on my funkwhale instance.
The ones with an ❌ respond with a 404, the ✅ ones give an actual response.
This is for future reference so there is an overview which parts of the Subsonic API work with funkwhale.

✅ ping
✅ getLicense
✅ getMusicFolders
✅ getIndexes
❌ getMusicDirectory
✅ getGenres
✅ getArtists
✅ getArtist
✅ getAlbum
✅ getSong
❌ getVideos
❌ getVideoInfo
❌ getArtistInfo
✅ getArtistInfo2
❌ getAlbumInfo
❌ getAlbumInfo2
❌ getSimilarSongs
❌ getSimilarSongs2
❌ getTopSongs
❌ getAlbumList
✅ getAlbumList2
✅ getRandomSongs
✅ getSongsByGenre
❌ getNowPlaying
✅ getStarred
✅ getStarred2
❌ search
❌ search2
✅ search3
✅ getPlaylists
✅ getPlaylist
✅ createPlaylist
✅ updatePlaylist
✅ deletePlaylist
❌ retrieval
✅ stream
❌ download
❌ hls
❌ getCaptions
✅ getCoverArt
❌ getLyrics
✅ getAvatar
❌ annotation
✅ star
✅ unstar
❌ setRating
✅ scrobble
❌ getShares
❌ createShare
❌ updateShare
❌ deleteShare
✅ getPodcasts
✅ getNewestPodcasts
❌ refreshPodcasts
✅ createPodcastChannel
✅ deletePodcastChannel
❌ deletePodcastEpisode
❌ downloadPodcastEpisode
❌ jukeboxControl
❌ radio
❌ getInternetRadioStations
❌ createInternetRadioStation
❌ updateInternetRadioStation
❌ deleteInternetRadioStation
❌ getChatMessages
❌ addChatMessage
❌ management
✅ getUser
❌ getUsers
❌ createUser
❌ updateUser
❌ deleteUser
❌ changePassword
❌ getBookmarks
❌ createBookmark
❌ deleteBookmark
❌ getPlayQueue
❌ savePlayQueue
❌ library
❌ scanning
❌ getScanStatus
❌ startScan

Thank you for you work, actually listening using Sonixd right now 😃

**Comment by jeffvli** [comment]
Glad you like it, and thanks for the API reference!
