### ISSUE TITLE
Add function keys support 

### ISSUE THREAD

**Issue by demogorgonz** [jeffvli/sonixd#139]
Functions keys are a must have option to play/pause, change songs and similar actions (depending on keyboard layout or mapped actions)

**Comment by jeffvli** [comment]
What do you mean by function keys? If you're talking about keyboard media keys (play/pause, play, stop, etc.), then they're already supported by default, and globally if you tick the `Enable global media keys` setting.

If not media keys, are you asking for separate hotkeys like:
- CTRL + Q = Skip to next
- CTRL + E = Skip to previous track

**Comment by demogorgonz** [comment]
Talking about media keys, sorry didn't knew there was an option to `enable global media keys` , this probably should be enabled by default. Thank you.
