### ISSUE TITLE
Play all Songs (Shuffled)

### ISSUE THREAD

**Issue by FrozenSource** [jeffvli/sonixd#143]
**Is your feature request related to a problem? Please describe.**

Hello, I might be missing it for some reason. But is there any way to just shuffle all songs.
I am using navidrome and am not familiar with their or airsonic's APIs but it would be a great feature since I like to shuffle a lot through my whole collection instead of always choosing an album.

**Describe the solution you'd like**

Great a Songs and possible Artists view next to the great albums functionalities. With the most important feature to shuffle them all.

**Describe alternatives you've considered**

-

**Additional context**

-

**Comment by jeffvli** [comment]
Use the "Auto playlist" on the Now Playing page (or on the mini player). It plays a random assortment of songs from your entire library.
![image](https://user-images.githubusercontent.com/42182408/146448496-b246b349-d79e-4012-a9f4-87c4a2047ba0.png)

**Comment by FrozenSource** [comment]
Thanks will try that.

**Comment by jacktheripper19** [comment]
I suggest adding the option in the dashboard section. That the natural place I think. You could also add a category in addition to the others (recently played, recently added, ...) and put a playlist for each genre horizontally

**Comment by jeffvli** [comment]
Added a song list page and removed the limit on the auto playlist for Jellyfin.
Going to close this for now, additional dashboard improvements may come later!
