### ISSUE TITLE
significant increase in power consumption during music playback

### ISSUE THREAD

**Issue by mueslimak3r** [jeffvli/sonixd#145]
**Describe the bug**
I installed the app via the AUR, which is an App-Image.
When after I start playing music, even with sonixd minimized, I see very high power drain when monitoring with powertop. This high power drain isn't present when the app is open and not playing mu

**To Reproduce**
1. install `Sonixd` from the `AUR` and open it
2. install `powertop` and open it
3. observe the power consumption with sonixd closed, open and not playing, and open and playing music

**Expected behavior**
Power consumption should be significantly lower. 11.5W is on the high end of that I observe while watching youtube in chrome

**Screenshots:**

App open and playing music:

![sonixd-open-playing](https://user-images.githubusercontent.com/28824542/146626608-b0681f54-0a92-4199-812d-84479ec4a422.png)

App open and not playing music:

![sonixd-open-not-playing](https://user-images.githubusercontent.com/28824542/146626620-232ed5e2-6c9c-4f6d-9332-dadff5e6e4f3.png)

App closed:

![sonixd-not-open](https://user-images.githubusercontent.com/28824542/146626626-0099e364-2777-457b-ad2f-65569b2bed19.png)

**Desktop (please complete the following information):**
 - OS: Manjaro - MATE Desktop
 - Kernel 5.15.7
 - App version: 0.10.0 from the AUR

**Comment by Maxplosion** [comment]
just curious does your cpu load also spike when you listen to music with sonixd? (Personally on windows (last checked with ver0.9) I see very little to no cpu/ram consumption, and that with an electron base of sonixd, so I was rather impressed here!)

**Comment by mueslimak3r** [comment]
> just curious does your cpu load also spike when you listen to music with sonixd? (Personally on windows (last checked with ver0.9) I see very little to no cpu/ram consumption, and that with an electron base of sonixd, so I was rather impressed here!)

Yeah I'm seeing at least one cpu core hit around 50% and the others in the 10-20% with music playing. and which core is around 50% changes quite rapidly. As soon as I pause the music it drops to 0-1% on all cores.

I'm on an 11th gen i5 (i5-1135G7), 32GB ram, it's the "Framework" laptop

**Comment by Maxplosion** [comment]
Here's some information from an older win10 notebook withi7-6700HQ and 16GB of ram using sonixd with jellyfin backend. 
I'm hovering from 4.5 to 6% total cpu while playing some opus tracks with around 200mb of memory, also tested with a rather large high res flac file (just to be sure) and same here (both direct playing). Player shown, if minimized cpu drops by like 1-2% total and ram also slightly drops. 
Regarding single cores (with HT) highest core is around 20-23%, 3 other hover at around 8-10% and the rest has close to nothing. Those cores usages are all static, so there is no swapping in the highest one or any others.

**Comment by jeffvli** [comment]
I'm 99% sure the reason is due to setting the player's current seek into redux state on every polling intervel. If you take a look at the Player component and check both the gapless and crossfade listen handler functions, it's called there. This can be a noticeable hit on CPU especially with low pollling intervels since it's setting the state quite a few times per second.

It's definitely not optimal at this point so I'll probably look into seeing if I can handle that logic in a cleaner way.

**Comment by mueslimak3r** [comment]
Thanks for the info!
