### ISSUE TITLE
Native titlebar option

### ISSUE THREAD

**Issue by gelaechter** [jeffvli/sonixd#148]
**Is your feature request related to a problem? Please describe.**
I prefer the native titlebar over your custom ones.

**Describe the solution you'd like**
I'd like to be able to choose Native as a titlebar style

**Additional context**
I created a native-titlebar branch on my fork which implements this, though I don't know if there is a better solution to style the app other than props. I never worked with React. 
I would've also implemented a way to have the option to restart the application from a whisper after changing the titlebar, but I don't know how to properly do that since electron and webpack are two processes.

**Comment by jeffvli** [comment]
That's a good idea, I'm ok with accepting a PR for this.

I took a look at your branch, and yes props for the styled components are fine. 

To reload, you would need to write a new `ipcMain` function for a 'reload' action. Send the 'reload' action from the reload handler on the frontend which then calls the `app.quit()` and then run the window creation function again.
```
app
  .whenReady()
  .then(() => {
    createWindow();
    createTray();
    return null;
  })
  .catch(console.log);
```

I'm not 100%  sure of this solution but I think that's how it should be done.
