### ISSUE TITLE
Parse lyrics and display them in bigger window box

### ISSUE THREAD

**Issue by jacktheripper19** [jeffvli/sonixd#151]
**Is your feature request related to a problem? Please describe.**
The ability to parse lyrics from .lrc file or embedded metadata/tags and display them along with a bigger display for the currently playing song.

**Describe alternatives you've considered**
This feature is already implemented in Elisa the media player from KDE:
https://invent.kde.org/multimedia/elisa/-/merge_requests/231

**Comment by jeffvli** [comment]
Did you want the lyrics to appear inside the Sonixd client or be passed into the MPRIS spec?

**Comment by jacktheripper19** [comment]
I don't know what benefit you get from passing lyrics into MPRIS but showing them inside Sonixd would be a good first step. The way I imagine it for the ui would be either:
- when a song is playing, if the user clicks on its image or name down in the player (in the current version, it only shows a pop up window for the artwork), a full screen window appear inside Sonixd showing the artwork, some relevant information about song like the writer, publisher, release year, .... + lyrics in the side if existent. (similar to how it is in KDE Elisa for example)
- In the list view for songs, add an icon in a new column to indicate the existence of lyrics. When clicked a pop up window shows up with only the lyrics and could be closed to go back to the previous view. (similar to how it is in Deezer client).

**Comment by jeffvli** [comment]
Thanks for the clarification. I wasn't quite sure where you wanted the lyrics since you mentioned Elisa media player.
I'll look into adding lyrics support like how you mentioned.

**Comment by jeffvli** [comment]
Started to take a look at this for 0.12.0.

## Subsonic
Has support for lyrics using the `/getLyrics` endpoint but there's no way of knowing a song has existing lyrics until that specific endpoint is called. 

> In the list view for songs, add an icon in a new column to indicate the existence of lyrics. When clicked a pop up window shows up with only the lyrics and could be closed to go back to the previous view.

That means that adding a new column to the list view wouldn't be possible unless `/getLyrics` was called for every song in the list which would not scale well. I'll look into adding it into the cover art hover like you specified as well as eventually adding a new context menu option to display a modal of the song details.

## Jellyfin
Currently no way to parse lyrics? https://features.jellyfin.org/posts/285/add-lyrics-to-songs

**Comment by jacktheripper19** [comment]
I don't know if this could help but from my search I found tuon music box, a similar client only on linux that has this feature implemented. Maybe looking into their implementation could inspire.

**Comment by jeffvli** [comment]
![image](https://user-images.githubusercontent.com/42182408/151265025-c32cc308-05f2-4c30-b728-ff6a92c45447.png)

Added a separate button to display the lyrics modal.
I decided to separate it from the cover art since I couldn't find a good way to style it together. The cover art hover has since been removed, and clicking it now brings up a modal of the full-size image.
