### ISSUE TITLE
Titlebar Style - none

### ISSUE THREAD

**Issue by atropos112** [jeffvli/sonixd#156]
Hello there, 

First of all well done for creating such beautiful app. I am a Linux user on a tiling window manager as such title-bar is somewhat redundant as I never minimize or maximize and always close with a hotkey. I've noticed you have two styles. windows and apple like title bar, would it be possible to also have no tittle bar at all. It is cleaner more minimalist look, with a lot of apps (say electron ones) coming without it by default.

**Comment by jeffvli** [comment]
Hi, this is already being worked on in #148!
