### ISSUE TITLE
Info mode panel - show more info abou music, artists, albums

### ISSUE THREAD

**Issue by Abraka** [jeffvli/sonixd#160]
I must say, that I am very positively surprised with sonixd. I never regulary used any desktop player for my *sonic servers before, mostly because they was, slow, ugly, lagging and have lots of functional problems, so I did use only web interface. But sonixd change that and is abble to handle my 500000 songs managed by airsonic-advanced platform. So far no other external client for my *sonix server was abble to handle this. 
So after several hours with sonixd I have few suggestions - feature reguest:
1. when I click on "now playing" it not showing album name
2. same here
3. It would be a great to have something like "Advanced info panel" when playing songs. For audio enthusiasts is important not only listen to music, but often they also want to see info about artist bio, album, similiar artist, have song recommendations for them etc.
Inspiration for this could be find in rompr project for example. Author of this player invest lot of thoughts and time into how to show user lot of information about his collection-music https://fatg3erman.github.io/RompR/ . 
4. ability to rate song in player
5. double click to show active queue when "info" mode
6. option for get rid of scrollbars, they are distractive

![sonix-changes](https://user-images.githubusercontent.com/6759588/147372239-9a582618-3095-41dd-bf8e-245b0d19f8b0.png)

**Comment by jeffvli** [comment]
These are great suggestions! I've been thinking for a while now that the Now Playing page has been a bit barebones, and this gives me a pretty good baseline to start.

**Comment by Abraka** [comment]
Im glad to hear that! This project of yours, together with airsonic-advanced could be the best thing to happen in music players domain on linux desktop for last 10 years....since amarok2 died. There is definitelly a great potential and I thing that lot of music enthusiasts will love sonixd after it reach some maturity. Keep up good work man!
