### ISSUE TITLE
[Linux] KDE's MPRIS tray applet tooltip displays the app description instead of the app name as the currently playing application.

### ISSUE THREAD

**Issue by Nocifer** [jeffvli/sonixd#163]
**Describe the bug**
Going by the provided screenshot, the tooltip should read "by The Temptations (Sonixd)" or something similar, instead of "The Temptations (A full-featured Subsonic API compatible cross-platform desktop client)"

**Screenshots**
![2021-12-25_15:52:40](https://user-images.githubusercontent.com/6195422/147386483-a637c0ca-2cd9-4f25-80de-b8e22b0eb228.jpg)

**Desktop (please complete the following information):**
 - OS: Arch Linux (KDE)
 - Version 0.10.0

**Comment by jeffvli** [comment]
Thanks for pointing that out, I'll fix it.
