### ISSUE TITLE
bug: sub menu in right click menu open while option is disabled

### ISSUE THREAD

**Issue by Emiliaaah** [jeffvli/sonixd#164]
**Describe the bug**
"Move selected to [...]" and "Set rating" option open if you move your mouse up and down over the options.

**To Reproduce**
1. open the right click menu on a song, playlist or album
2. do what I demonstrated in the video (this also works for the "Set rating" option)

**Expected behavior**
I expected for the sub menu to not open.

**Screenshots**
https://i.imgur.com/AeRgzvY.gif

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.10.0

**Comment by jeffvli** [comment]
I've noticed this as well. I'll see if I can add a fix for this.
