### ISSUE TITLE
Option to change album default sorting

### ISSUE THREAD

**Issue by JingAr87** [jeffvli/sonixd#169]
Right now, whenever I enter the album page, the sorting always defaults to random. That's kinda annoying for me, so it would be nice to add an option to change album default sorting. 

Also I'm not sure if I should open another issue for this, but it would be great to load the 100% quality album cover(jellyfin) whenever mouse over the cover at the bottom left corner.

**Comment by jeffvli** [comment]
Sure, I'll take a look at these!

**Comment by GermanDarknes** [comment]
Started a branch with this, will see if I can fix the action errors.

https://github.com/GermanDarknes/sonixd/tree/feature-default-album-sort

**Comment by jeffvli** [comment]
Default album sort implemented by @GermanDarknes in #178 

The other request will be covered in #151.
