### ISSUE TITLE
Supysonic support (Subsonic API v1.10.x)

### ISSUE THREAD

**Issue by rossbates** [jeffvli/sonixd#170]
**Describe the bug**
When using Sonixd with a Supysonic backend the artist page fails to load.

**To Reproduce**
1. Click 'Artists' in the sidebar
2. Select an artist from the list
3. Progress indicator will display indefinitely preventing any additional user input 

**Expected behavior**
The artist's album list should load. A graceful fallback if supplemental artist metadata is unavailable (see notes).

**Desktop (please complete the following information):**
 - OS: Mac 12.1
 - Sonixd 0.11
 - Supysonic 0.7.1

**Notes**
Watching the supysonic log files during this you can see that the Sonixd client requests _getArtists_, then when an artist is clicked it's followed by _getArtist_ and _getArtistInfo2_. It's the second request to getArtistInfo2 that fires 4 times getting a 404 which causes the UI to hang indefinitely.

According to the Supysonic docs _getArtistInfo_ and _getArtistInfo2_ is on the roadmap

https://supysonic.readthedocs.io/en/latest/api.html#getartistinfo2

Would it be possible for Sonixd to handle this and load a fallback page for the artist album list? If not, perhaps just catch the error and warn the user so they can continue using the application. Currently the only way out of this is to kill and restart the app.

**Comment by jeffvli** [comment]
I think this is actually an issue with Supysonic not following the Subsonic API spec of returning a `HTTP 200` status for failed requests. I spent some time trying to fix this before I realized.

I have opened up an issue to see if this can be implemented on their side since it causes inconsistencies if I were to handle it specifically on my side (https://github.com/spl0k/supysonic/issues/228).

**Comment by jeffvli** [comment]
Supysonic support will be dropped for the time being until either I or someone else wants to implement better error handling for some endpoints. The current API target for Supysonic is 1.10.2, while Sonixd was written while targeting v1.15.0+ (though has been tested for 1.13.0).

For reasoning, see @spl0k's post [here](https://github.com/spl0k/supysonic/issues/228#issuecomment-1008014039).

**Comment by rossbates** [comment]
Thanks for looking into this. Totally understand that you're limited in what you can do without effectively removing functionality from the client. Sonixd is honestly such a good Subsonic client that I'll figure out a way around it. Really impressive work you've done here.

Currently I'm running a forked version of Supysonic modified to scrobble to the local database to preserve ownership and privacy. I might stub out getArtistInfo with some default data to see where I can take it. I believe the original Subsonic did this when last.fm changed their terms of service. Other clients like Play:Sub on iOS implement a similar approach.

I'll keep following this issue for updates. If on the other hand you choose to close it that's fine too. Thanks again!!

**Comment by jeffvli** [comment]
I pushed a dev build here [http://ftp.sonixd.com/](here) if you would like to test it out. Download a build for `Sonixd(dev)_2022-01-13...`.

**Comment by rossbates** [comment]
Nice! Works great. You can see Sonixd ask for getArtistInfo2 and getTopSongs then brush if off and keep moving along with no issues when it gets the 404s. You rock Jeff, time to buy you some coffee.

**Comment by jeffvli** [comment]
Appreciate the support, and glad it's working for you now!
