### ISSUE TITLE
Discord rich presence does not work

### ISSUE THREAD

**Issue by LilMistix** [jeffvli/sonixd#173]
**Describe the bug**
When activating the function for discord sonixd says "Error: could not connect"

**To Reproduce**
1. Go to "config"
2. Click on Other
3. Scroll down to "External > Discord"
4. Click on "Rich Presence"
5. See error

**Expected behavior**
Show the music I'm listening to on my discord profile

**Screenshots**
![image](https://user-images.githubusercontent.com/89847202/148260830-4895e382-e226-4977-ab7d-56e83aebc154.png)

**Desktop:**
 - OS: Ubuntu 20.04
 - Version 0.11.0

**Comment by LilMistix** [comment]
My problem is resolved, it was because I used the snap discord instead of deb

**Comment by jeffvli** [comment]
Glad you resolved it! I'm assuming the [discord-rpc](https://www.npmjs.com/package/discord-rpc) library that I use doesn't properly detect your snap installed instance.
