### ISSUE TITLE
How can I contribute to translation?

### ISSUE THREAD

**Issue by shanyan-wcx** [jeffvli/sonixd#174]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jeffvli** [comment]
Translation support is currently being worked on in #146. Once that is implemented and merged, additional documentation will be added for contributors.

Thanks in advance 😀.

**Comment by jeffvli** [comment]
Some simple instructions for translation contributors: https://github.com/jeffvli/sonixd/discussions/215#discussioncomment-2093320
