### ISSUE TITLE
Add "Songs" page for jellyfin

### ISSUE THREAD

**Issue by kisenera** [jeffvli/sonixd#177]
**Is your feature request related to a problem? Please describe.**
The only way to shuffle all tracks seems to be auto playlist, and it has a limit of 500 tracks.

**Describe the solution you'd like**
Either a "Song" menu that shows the entire library in a playlist or the ability for auto playlist to use more than 500 tracks.

**Comment by jeffvli** [comment]
I can add this for Jellyfin, but just a note that Subsonic's API doesn't expose a song list.
