### ISSUE TITLE
[FEAT/Gnome] Integrate the app with Gnome's media controls.

### ISSUE THREAD

**Issue by dusnm** [jeffvli/sonixd#183]
Currently the app doesn't integrate at all with Gnome's media controls, like any native media player would do.
I'd like that to be added if possible as that's a feature that many Gnome users, including myself use all the time.
It's very inconvenient to go looking for the application window just to pause a song.
I've tried using media controls on my keyboard, but that too doesn't work.

**Comment by jeffvli** [comment]
Gnome's media player should already be supported by the implemented MPRIS player. Do you see the current song / artwork on the player?

You can also try using [playerctl](https://github.com/altdesktop/playerctl) to map keys to the media controls.

**Comment by ilyazzz** [comment]
The media controls work fine for me in Gnome with no extra configuration. Running Fedora 35 and sonixd 0.11 AppImage.

**Comment by jeffvli** [comment]
Closing since MPRIS is supported.
