### ISSUE TITLE
Album shows blank but songs can be found via search and played

### ISSUE THREAD

**Issue by talentedmrripley** [jeffvli/sonixd#195]
**Describe the bug**
Album shows no tracks available, and is missing cover art, but songs can be played if searched for by title.  Tracks and cover art do show up in Madsonic.

**To Reproduce**
1. Go to album, see no tracks
2. Search for track by title
3. Play individual song

**Expected behavior**
Be able to see and play tracks under album listing

**Screenshots**
Album listing
![image](https://user-images.githubusercontent.com/10006695/149952825-ad4d9931-3a25-403d-8b72-a89798a30c8c.png)
Artist page
![image](https://user-images.githubusercontent.com/10006695/149954616-bf20819c-6ec4-4738-85a1-4152cc515d34.png)
Song found via search
![image](https://user-images.githubusercontent.com/10006695/149953120-8ce264a7-72d9-4606-b1e8-b837a96692ec.png)
MadSonic
![image](https://user-images.githubusercontent.com/10006695/149953265-e31cf3c8-f65d-4c70-bdf5-c9cd4b538bb3.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10
Sonixd
Current version: 0.11.0
Latest version: 0.11.0
Node: 14.16.0
Chrome: 91.0.4472.164
Electron: 13.6.3

**Additional context**
So far I've only noticed this on one album but I haven't checked every album yet.  The album in Sonixd appears to contain no tracks.  Hitting the play button for the album says playing 0 tracks and nothing happens.  I found that I can search for tracks by title and play them.  Also some tracks appear on the artist page and can be played from there.

**Comment by jeffvli** [comment]
Can you check what the madsonic API response is returning for that album?
You can either run Sonixd with [debugtron](https://github.com/bytedance/debugtron) to view the network requests in the web tools or you can run the requests on a browser.

```
# Replace http://localhost:4040 with the URL to your madsonic server
# Replace "USERNAME" and "PASSWORD" with your credentials

http://localhost:4040/rest/search3?query=girl%20going%20nowhere&u=USERNAME&p=PASSWORD&f=json&c=test&v=1.15.0

# Find the id of the "Girl Going Nowhere" album and copy it
# Replace ID with the id of the above album and replace USERNAME and PASSWORD with your credentials

http://localhost:4040/rest/getAlbum?id=ID&u=USERNAME&p=PASSWORD&f=json&c=test&v=1.15.0
```

Can you copy the `/getAlbum` response for me?

**Comment by talentedmrripley** [comment]
Looks like it some issue with MadSonic.  It isn't returning the list of tracks, but other album IDs are.  A rescan of the media folders didn't change that.  Not sure what's going on but it isn't with SonixD.  Thanks for the quick response.  Closing this issue.


`{
   "subsonic-response" : {
      "status" : "ok",
      "version" : "1.14.0",
      "type" : "subsonic",
      "album" : {
         "id" : "1947",
         "name" : "Girl Going Nowhere (Atlantic 566217-2)",
         "artist" : "Ashley McBryde",
         "artistId" : "2202",
         "coverArt" : "al-1947",
         "songCount" : 11,
         "duration" : 2428,
         "playCount" : 95,
         "created" : "2020-04-14T00:41:55.400Z",
         "year" : 2018,
         "genre" : "Country"
      }
   }
}`
