### ISSUE TITLE
Albums as grid/list instead of carousel 

### ISSUE THREAD

**Issue by Maxplosion** [jeffvli/sonixd#199]
Hi, 
I might not have found it, but is there a way to display the albums of an artist, when in the artist detail view, as a grid list instead of as a carousel? With artists that release mostly singles that have let's say 30+ of them this is impractical as it's not possible to see all of them at once due to the carousel. 
BR

Sidebar > Artists > select artist > detail view of artist and their albums (in here)

**Comment by jeffvli** [comment]
Either click on the `View Discography` button or click on the `Latest Albums` title of the carousel.

There's an issue on Jellyfin with the album artist only showing `Appears On` though, so you'll need to click into one of the artist's albums and click on the artist link from there.

**Comment by Maxplosion** [comment]
Hi, 
yes exactly, to show the albums already on the detail view like they are in the grid/list in `View Discography` would be my request, as it's one extra click, which might not be much, but while browsing through artists that gets tedious and kind of destroys the flow a little bit. (And I'm in general not a fan of carousel views for most stuff, I like to see all content at once, makes it easier for me to find stuff and spot differences. Also dislike it on e.g. Spotify, so not specific to here)

Ps. `Appears On` works fine for me on JF

**Comment by jeffvli** [comment]
I can add a toggle to set the default view when entering the artist page.

**Comment by Maxplosion** [comment]
that would be greatly appreciated, thank you!

**Comment by jeffvli** [comment]
Added this setting toggle which will bring you directly to the album list on the artist page:
![image](https://user-images.githubusercontent.com/42182408/151489769-09d75316-e2af-441b-a86c-d389da8461f9.png)
