### ISSUE TITLE
Media keys not working (Logitech MK700)

### ISSUE THREAD

**Issue by Venom1991** [jeffvli/sonixd#200]
**Describe the bug**

Hi there, thank you for creating this app - it's working great with my Airsonic server!

I only have one small issue, that is the media keys do not work properly at all - either as global keys or while the app has focus.
The keyboard is [this](https://www.amazon.com/Logitech-Wireless-Desktop-MK700-Keyboard/dp/B002KQ5KVG) one and it does have media keys. The volume keys work just fine but those are handled directly by the OS, I suppose.

I've enabled the "Global Media Hotkeys" option and no other app (to the best of my knowledge) is using those keys. Also, I saw that a possible solution is setting the app which you want to respond to these keystrokes as the default audio player app but sonixd isn't listed there (in the Default apps -> Music player menu).  
I've also tried restarting the HID Service but that didn't help.

Global hotkeys work fine for example in AIMP or MusicBee but I'm not using the keyboards media keys for those but rather my own combination of keys comprised of a standard set of keys, found on every keyboard. I've disabled global hotkeys in both of those players, just to be sure.

Logitech[ SetPoint](https://support.logi.com/hc/en-nz/articles/360025141274) is also installed and running just fine. I've also tried running it with elevated rights but that made no difference, unfortunately.

Perhaps it'd make sense if sonixd also allowed the user to define their own combinations of keys, for playback control (global or otherwise)?

Thank you in advance!

**To Reproduce**
- go buy the linked keyboard ;)
- open the app and try the media keys (previous/next track, play/pause)
- nothing really happens

**Expected behavior**
- media keys actually control the playback

**Desktop (please complete the following information):**
 - OS: Windows 10 21H2
 - 19044.1469

**Comment by jeffvli** [comment]
I took a look around and possibly some of the comments in this issue could point to a solution: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/90. If that doesn't work, then I would suggest using an AutoHotkey script to set custom key combinations for the media controls since that would meet your current use case.

> Perhaps it'd make sense if sonixd also allowed the user to define their own combinations of keys, for playback control (global or otherwise)?

This is something I've thought about, but haven't gotten around to implementing yet. Maybe soon!

**Comment by Venom1991** [comment]
@jeffvli 
Thank you, I'll try your suggestion and report back, as soon as I can.

As far as that feature, it'd be lovely but do take your time, of course.
It's just too bad that there is no MPRIS equivalent for Windoze... It works wonderfully on Linux.

**Comment by Venom1991** [comment]
Logitech uberOptions are a no-go, it seems:

> Other keyboards supported by SetPoint that I haven't yet uberfied (but I probably could):
>     Cordless Keyboard (Cordless Internet Pro Desktop, EX90)
>     - EX 100 Keyboard
>     - K300 Compact Corded keyboard
>     - K340 Unifying Cordless keyboard
>     - B550 Unifying(?) Cordless Keyboard
>     - K700 Unifying(?) Cordless keyboard
>     - MK700 Cordless keyboard
>     - N305/B505 Unifying Cordless Number Pad
> 

Ok then, I'll try the AutoHotkey approach instead.

**Comment by Venom1991** [comment]
> Another user pointed me towards [this thread](https://yabb.jriver.com/interact/index.php?topic=25426.0) which you may want to try as well.

Yep, changing the SetPoint's user.xml file does indeed work but I'm going to try the AHK approach, as well, simply because the keyboard itself doesn't have a dedicated Stop button which I find annoying.

**Comment by Venom1991** [comment]
```
#SingleInstance, Force
SendMode Input
SetWorkingDir, %A_ScriptDir%

; AutoHotkey Media Keys (inspired by https://gist.github.com/mistic100/d3c0c1eb63fb7e4ee545)
^!Home::Send       {Media_Play_Pause}
^!End::Send        {Media_Stop}
^!PgUp::Send       {Media_Prev}
^!PgDn::Send       {Media_Next}
```
So these key combinations are, when expanded, Ctrl+Alt+(Home | End | PageUp | PageDown).

All of these work fine but the "Media_Stop" mapped key which, once invoked, results in sonixd becoming "confused" (for lack of a better word), like so:

![Sonixd_0qAYCuLgvG](https://user-images.githubusercontent.com/5722469/150638073-89e035c6-1736-47a0-9a20-5078a154f54f.png)

**Comment by Venom1991** [comment]
@jeffvli 

Hm, it seems that the [stop](https://github.com/jeffvli/sonixd/blob/9a13ed2dc265def9e01fcf7164e4c693badb39e8/src/main.dev.js#L110) lambda is invoked for both local and global key shortcuts (makes sense, of course) but its implementation is a bit weird (from my perspective, at least) because it empties the current play queue and then tries to pause the playback on an empty queue (hence there is no song to pause, really).  
Also, the same status ("PAUSED") is reused for both stop and pause actions which is also somewhat confusing.

I hope you don't mind me trying to investigate this on my own.

Shortcut registering:
```
// global
globalShortcut.register('MediaStop', () => {
  stop();
});
```
```
// local
electronLocalshortcut.register(mainWindow, 'MediaPlayPause', () => {
  playPause();
});
```

"stop" lambda":
```
const stop = () => {
  const storeValues = store.getState();
  const currentEntryList = getCurrentEntryList(storeValues.playQueue);

  if (storeValues.playQueue[currentEntryList].length > 0) {
    store.dispatch(clearPlayQueue());
    store.dispatch(setStatus('PAUSED'));
  }
};
```

**Comment by jeffvli** [comment]
What's your expected outcome from pressing the `stop` key?

My thoughts are that `play/pause` already covers the use case for stopping and starting the current song, while `stop` clears the queue.

**Comment by Venom1991** [comment]
> What's your expected outcome from pressing the `stop` key?
> 
> My thoughts are that `play/pause` already covers the use case for stopping and starting the current song, while `stop` clears the queue.

Well, in every other media player (hardware based ones included) that I've ever used `stop` behaves in almost exactly the same way as `pause` does with an additional step of resetting the currently played track to the zero second mark. Of course, it shouldn't do anything if there is no currently played song to reset in the first place.  
Perhaps you've used a player which behaves like sonixd does, with regards to the `stop` feature?

**Comment by jeffvli** [comment]
I can change the behavior. I was basing it off the web players of Plex/Jellyfin which clears the queue upon the player stopping.

Tested it on foobar2000 and it does perform the behavior you listed.

**Comment by Venom1991** [comment]
> I can change the behavior. I was basing it off the web players of Plex/Jellyfin which clears the queue upon the player stopping.

Sure, that'd be great.  
You can make it configurable so as not to perhaps confuse current users who've gotten used to this behavior (which would then become the default one) by using sonixd and/or those web-based players which you've mentioned?

**Comment by jeffvli** [comment]
I've adjusted the `stop` behavior to pause the player and reset the seek to 0 instead of clearing the queue. I'm just going to force that behavior instead of adding another toggle since there's already too much complexity with the player logic.

**Comment by Venom1991** [comment]
> I've adjusted the `stop` behavior to pause the player and reset the seek to 0 instead of clearing the queue. I'm just going to force that behavior instead of adding another toggle since there's already too much complexity with the player logic.

That's great news, thank you so much for your commitment to this project!
