### ISSUE TITLE
Enable sonixd integration with Windows media controls

### ISSUE THREAD

**Issue by krptg0** [jeffvli/sonixd#201]
**Is your feature request related to a problem? Please describe.**
It's not a problem !

**Describe the solution you'd like**
Media keys on my keyboard are working fine, but sonixd is not registering onto Windows media control, like Spotify or even Navidrom on Chrome/Edge does (artwork, play buttons, next to the volume slider)

**Describe alternatives you've considered**
At this time, none.

**Additional context**
I've been extensively using those controls with Spotify in order to see which song is playing right from my volume slider, it's a QoL feature, basically.

Thank you for this awesome piece of software by the way @jeffvli  ;)

**Comment by GermanDarknes** [comment]
[#](https://github.com/jeffvli/sonixd/pull/171)

Can you look at this PR if it's the feature you want? It already got merged and will be in the next release.

**Comment by krptg0** [comment]
@GermanDarknes it absolutly is, thank you :)
