### ISSUE TITLE
Single songs are played twice despite repeat being off

### ISSUE THREAD

**Issue by internetfreak** [jeffvli/sonixd#205]
**Describe the bug**
When playing selected songs via search or by just selecting them from an album which results in a queue with only that one particular song, it gets repeated as soon as the playback ended.

**To Reproduce**
1. Pick for any song, either from search or from the album view
2. Rightclick on it, select "play"
3. Wait for the song to finish
4. Even though playback has technically ended, the song will be played again

**Expected behavior**
Playback ends if there's nothing else to play

**Screenshots**
No applicable screenshots here

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 0.11

**Additional context**
If I may take a wild guess, I would assume the problem is the crossfade/gapless playback. From what I remember the problem occured with different settings, I have currently the preset for gapless playback active. If you need any additional info, I am willing to provide them

**Comment by QuestionableBaboon** [comment]
Thanks for raising this, I logged on to flag this very issue.

Adding that this also occurs on MacOS 12.2 and the latest build of Sonixd.
Similar to the above, I have gapless playback enabled.

Indeed, it appears a single track will play endlessly, and I've confirmed that loop is off. 
Further the playhead and song time will reset and remain at zero after the first playthrough whilst the same track continues.

Thank you!

**Comment by jeffvli** [comment]
Thanks @internetfreak for reporting this issue and @QuestionableBaboon for confirming!

I've also confirmed this on my side, though I'm surprised this hasn't been caught sooner. I guess it's pretty rare that I only have a single song in my queue during normal listening.m surprised this hasn't been caught sooner. I guess it's pretty rare that I only have a single song in my queue during normal listening.

I've put in a fix that will be introduced in the next release.
