### ISSUE TITLE
Customize side bar?

### ISSUE THREAD

**Issue by mill1000** [jeffvli/sonixd#206]
I'm impressed with the Look & Feel customization of this application. 

The only thing I haven't been able to find is how to customize the entries in the side bar. I don't make use of Playlists, Favorites, or Genres and I would like to remove them from the side bar.

**Comment by jeffvli** [comment]
I've been thinking of reworking the sidebar for a while now (still not sure exactly how it'll be styled).
I'll keep into consideration the adding/removal of sidebar elements when I do!
