### ISSUE TITLE
wrong behavior in Previous|Next track function 

### ISSUE THREAD

**Issue by jacktheripper19** [jeffvli/sonixd#207]
**Describe the bug**
Hello, I'm reporting a bug in the the previous|next track functions behavior, two things are wrong with the implementation:
- When playing the first song of an album or one song using previous track should replay the current song as it is the case for other media players. Currently, it just stops playing because there is no song before( probably looks for song id=-1 in the queue so it freezes)
- Usually in other media players, if the users plays a song for an amount of time greater than a threshold seconds (let's say 3 seconds) then click on previous track, the player replay the current song. Else if it is played for less than the threshold and the user click previous track it will look for the previous track as expected except when the current song is the first on the queue or of the album, then it will keep on replaying that first song when using calling previous track function.
The bug happens with UI button as well as physical media keys.
- Something similar happens for next track function. When calling it on the last song in a queue, it stops playing and the UI feedback is not correct. Usually in other players, in that situation, either the last song should continue playing, therefore the user understands that it is the last in the queue or it stop playing and empty the queue and clear all its lists.

**To Reproduce**
1. Play a song or first song in a queue
2. Click on previous track
3. See that the player freezes

Do the inverse for the last song in a queue and use next track.

**Expected behavior**
- Previous track function should replay the current song if it was played for an amount of time greater than a threshold  or if it's the first in the queue else play the previous song.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Manjaro KDE
 - Version: Latest

**Comment by jeffvli** [comment]
Thanks for noting this behavior. It was definitely a bit wonky due to the gapless/fade implementation.

I've made the following changes based on your recommendations:
- Pressing "prev" within 5 seconds of song start goes to previous song
- Pressing "prev" after 5 seconds goes to the start of the song
- Pressing "prev" on the first song of the queue with repeat "off" goes to the start of the song
- Pressing "next" on the last song of the queue with repeat "off" does nothing

**Comment by jacktheripper19** [comment]
Thank you and good job.
> I'm going to leave the queue in place since I think it should be up to the user to clear it if they want.
In that case, the UI should also consider this: Currently when the last song in the queue is finished playing, the 'Play|Pause' button stays in 'Pause' and you have to click it twice if you want to replay that last song. Usually when the last song is finished playing, that button switch to 'Play' and you only have to click it once to play the song.

**Comment by jeffvli** [comment]
Done :)
