### ISSUE TITLE
DBus errors when interacting with songs

### ISSUE THREAD

**Issue by jimtjames** [jeffvli/sonixd#208]
**Describe the bug**
Upon interacting with a song (Playing, skipping pausing, seeking, etc.) dbus error messages are displayed. However, song playback continues normally.

**To Reproduce**
1. Play a song
2. First error message should pop up. Click OK.
3. Second error message will pop up.

**Expected behavior**
No error messages should appear.

**Screenshots**
[Screenshots of two error messages here](https://imgur.com/a/aiJBgaY)

**Desktop (please complete the following information):**
 - OS: KDE Neon 20.04
 - Version 0.11.0 (This issue does not occur in 0.10.0)

**Additional context**
N/A

**Comment by jimtjames** [comment]
Upon some further testing this seems to be an issue purely related to my server. Closing.

**Comment by jeffvli** [comment]
I was going to take a look at this later today but honestly wasn't quite sure why the error was occurring since I've tested this with KDE as well. Can you share how you determined this was a server issue just in case someone else runs into this in the future?

**Comment by jimtjames** [comment]
I was originally using [Nextcloud/Owncloud Music](https://github.com/owncloud/music), which exposes a Subsonic API endpoint. I switched over to Navidrome and suddenly the issue went away.

I don't think this makes a difference, but I'm on KDE Wayland, not X11. That being said, the error occurred on both XWayland and Wayland.
