### ISSUE TITLE
On windows, the white screen appears when the playlist is deleted

### ISSUE THREAD

**Issue by shanyan-wcx** [jeffvli/sonixd#216]
**Describe the bug**
On windows, the white screen appears when the playlist is deleted

**To Reproduce**
I created an empty playlist, and then I tried to delete it. The program went straight to the white screen.

**Expected behavior**

**Screenshots**
![屏幕截图 2022-02-02 140300](https://user-images.githubusercontent.com/58252651/152101418-a242fe1b-575a-4dec-9460-fdb66cb59324.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 0.12.0

**Additional context**

**Comment by jeffvli** [comment]
What server are you using?

**Comment by jeffvli** [comment]
Thanks for reporting, will release a hotfix shortly.
