### ISSUE TITLE
Toggle for Artist instead of Album Artist for now playing track 

### ISSUE THREAD

**Issue by Maxplosion** [jeffvli/sonixd#218]
**Is your feature request related to a problem? Please describe.**
The currently playing track in the lower left corner shows `Track/Album Artist/Album`. 
Could you maybe create a toggle in the settings to switch `Album Artist` to just `Artist`?

This would be useful for albums that have a general Album Artist with different Artist(s) for each track.

**Comment by jeffvli** [comment]
I ended up just changing it instead of adding a toggle since it makes more sense to have the artist there.
