### ISSUE TITLE
Order by bitrate compares strings and not the integer value

### ISSUE THREAD

**Issue by extremelf** [jeffvli/sonixd#220]
**Describe the bug**
When ordering by bitrate it shows in order compared as string type and by doing so for example we have (169 kbps, 201 kbps and 1000kbps) it will be shown in the order 1000 < 169 < 201 instead of 169 < 201 < 1000

**To Reproduce**
1. Go to 'songs'
2. Click on 'bitrate and order ascending'
3. See error

**Expected behavior**
The bitrates should be ordered by its integer value as stated in the description of the bug

**Screenshots**
![2022-02-03_22-41](https://user-images.githubusercontent.com/63683116/152441467-b97e3464-5030-4b79-bc42-14e26df11d25.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Version 0.12.0

**Comment by jeffvli** [comment]
Thanks for reporting this, accidentally set bitrate as a string.
