### ISSUE TITLE
Request to add Player logo to the Funkwhale applications page

### ISSUE THREAD

**Issue by AMoonRabbit** [jeffvli/sonixd#222]
Hello, just wanted to request permission for me to add the logo to Funkwhale's applications page here: https://funkwhale.audio/en_US/apps/

Funkwhale supports the subsonic API, and so far for me, this music player is working well as a desktop player, so if you're happy for me to, I would like to add it to the suggested apps list.

**Comment by jeffvli** [comment]
Sure, I don't mind!

**Comment by AMoonRabbit** [comment]
Thank you
