### ISSUE TITLE
Recently played plays album from 1st song instead of recently played

### ISSUE THREAD

**Issue by JingAr87** [jeffvli/sonixd#236]
In dashboard, if I have played a music from an album recently, and I click on the play button from the Recently played section. It plays the entire album from the 1st music instead of what's actually titled.

**Comment by jeffvli** [comment]
This is from the dashboard right (on Jellyfin)?

**Comment by JingAr87** [comment]
Yes, on jellyfin

**Comment by jeffvli** [comment]
Made changes that affect both the "Recently Played" and "Most Played" sections on the dashboard (since those both indicate individual songs).
