### ISSUE TITLE
Pre-startup crash on macOS 

### ISSUE THREAD

**Issue by woodruffw** [jeffvli/sonixd#237]
HI there! This project looks fantastic; thanks for creating it.

**Describe the bug**

I tried to download the latest version of sonixd (`0.13.0`) for macOS and start it.

The application fails to start: no windows appear except for a crash splash. Screenshots below.

**To Reproduce**

1. Download the latest release DMG
2. Open the DMG, drag the application to the Applications folder
3. Run sonixd via Spotlight

**Expected behavior**

I expected the application to start.

**Screenshots**

Apologies for the cramped screenshots; macOS makes it impossible to resize these.

<img width="263" alt="Screen Shot 2022-02-16 at 11 05 26 AM" src="https://user-images.githubusercontent.com/3059210/154306311-eee47dca-ad7e-4252-bdf7-ce6f49211c4e.png">

<img width="265" alt="Screen Shot 2022-02-16 at 11 05 52 AM" src="https://user-images.githubusercontent.com/3059210/154306406-55fb2139-8ccd-4ca5-8e6b-39dd9dedf16d.png">

**Desktop (please complete the following information):**
 - OS: macOS 
 - Version: 12.2.1 (x86-64)

**Comment by ChandlerSwift** [comment]
Alternatively, here's a text version of my crash log -- looks to be pretty similar:
```
Uncaught Exception:
TypeError: Cannot read property 'map' of undefined
    at Module.78118 (/Applications/Sonixd.app/Contents/Resources/app.asar/main.prod.js:2:1224390)
    at n (/Applications/Sonixd.app/Contents/Resources/app.asar/main.prod.js:2:1302639)
    at /Applications/Sonixd.app/Contents/Resources/app.asar/main.prod.js:2:1303150
    at Object.<anonymous> (/Applications/Sonixd.app/Contents/Resources/app.asar/main.prod.js:2:1303164)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Object.<anonymous> (electron/js2c/browser_init.js:193:3237)
    ```

**Comment by 0xAB51NTH** [comment]
![image](https://user-images.githubusercontent.com/47013267/154361728-681bfedd-c530-4fc0-96f2-de4d887d3ac7.png)
Seems like its not only a issue with macOS but with windows too, I have the same issue.

Windows 10 version 21H1 on newest sonixd release.

**Comment by jeffvli** [comment]
Thanks for reporting. Seems like I broke something regarding the default settings file creation.
Going to debug this.

**Comment by jeffvli** [comment]
Should be resolved in [0.13.1](https://github.com/jeffvli/sonixd/releases/tag/v0.13.1). Let me know if it still doesn't work.

**Comment by ChandlerSwift** [comment]
Can confirm -- works fine now. Thanks!

**Comment by woodruffw** [comment]
Confirming that it works for me as well. Thanks so much for the quick fix!
