### ISSUE TITLE
Add AARCH64 support

### ISSUE THREAD

**Issue by flossgeek** [jeffvli/sonixd#238]
**Is your feature request related to a problem? Please describe.**
At the moment this package does not have support for AARCH64 devices.

**Describe the solution you'd like**
AARCH64 support to use this package on ARM devices would be awesome.

**Comment by jeffvli** [comment]
Sure, I can take a look into adding support for them.

**Comment by jeffvli** [comment]
Builds with the new arch will be added for the next version. If you want to package it yourself on the current version you can use `yarn package --arm64`.
