### ISSUE TITLE
Playing directly from album symbol wrong orderer

### ISSUE THREAD

**Issue by KarBoeh** [jeffvli/sonixd#240]
**Describe the bug**
By right-klicking on album --> play the single album the tracks will be played not in correct order

**To Reproduce**
1. Generate library with certain albums
2. look for desired album
3. right click and select play
4. playlist is disordered, will be play not like being named / tracknumbering will be ignored

**Expected behavior**
Should be played by tracknumbering or filename-ordring (filenames are starting with tracknumber exactly as tagged

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 11

**Additional context**

**Comment by jeffvli** [comment]
Ah, I think I know what the issue is now. Are you playing the albums from the `Folders` page?

I just tested on there and those do seem to be out of order (which I need to fix), but playing the album from the `Albums` list works as expected.

**Comment by KarBoeh** [comment]
Yeah, I do like you wrote, exactly  :) normal albums would not too be too bad with this behavior,  but actullay I am listening albums needed to play gapless, mixed albums, divided into tracks with own fading and if they're played disordered, it really sounds cruel...Would be nice,  if the guys behind jellyfin would implement folder usage like it is in emby...Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Jeff ***@***.***> Datum: 18.02.22  15:41  (GMT+01:00) An: jeffvli/sonixd ***@***.***> Cc: KarBoeh ***@***.***>, Author ***@***.***> Betreff: Re: [jeffvli/sonixd] Playing directly from album symbol wrong orderer (Issue #240) 
Ah, I think I know what the issue is now. Are you playing the albums from the Folders page?
I just tested on there and those do seem to be out of order (which I need to fix), but playing the album from the Albums list works as expected.
