### ISSUE TITLE
Windows taskbar hover doesn't show song cover when using the new cover placement

### ISSUE THREAD

**Issue by JingAr87** [jeffvli/sonixd#242]
If I use the old cover placement in the player bar, it shows the cover just fine in taskbar hover. However, if I use the new cover placement at the sidebar, it shows the wrong thing instead. I've attached a few photos to show the issue. Latest v0.13.1.

![image](https://user-images.githubusercontent.com/89338247/154840841-7a2d7ab2-d10a-4df3-9ed0-5773e2fc9092.png)
![image](https://user-images.githubusercontent.com/89338247/154840852-11854bdd-5668-4ebe-9a5d-1d8dd731889c.png)

**Comment by jeffvli** [comment]
I may need to just remove the image from the taskbar thumbnail. I don't think there's a way to easily track the cover position between the original position and the sidebar (since the sidebar can be resized).
