### ISSUE TITLE
Removing the last item from the play queue results in Javascript error.

### ISSUE THREAD

**Issue by Nocifer** [jeffvli/sonixd#248]
**Describe the bug**
When you try to remove the last item from the play queue, the following error is printed:

![2022-03-03_12:28:28_Error](https://user-images.githubusercontent.com/6195422/156548502-86c7f325-89d5-4b48-a5ac-2d97639a6198.png)

**To Reproduce**
1. Add one or more tracks to the play queue.
2. Select them all, right click on them and choose "Remove selected"; or select them all but one and remove them, and then select the last remaining track and try to remove it by its lonesome; i.e. it makes no difference whether it's single or batch removal performed.

**Expected behavior**
Tracks should be removed cleanly.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version 0.13.1

**Comment by jeffvli** [comment]
Thanks for reporting, fixed!
