### ISSUE TITLE
Manipulating playback from the tray icon is not synchronized immediately with MPRIS

### ISSUE THREAD

**Issue by Nocifer** [jeffvli/sonixd#249]
**Describe the bug**

**To Reproduce**
1. Begin playback.
2. Open the MPRIS applet so you can observe its behavior.
3. After a few seconds of playback, click on Sonixd's tray icon and select Previous Track.
4. Playback restarts from the beginning, but MPRIS state is not reset and its seekbar keeps on going like nothing happened.
5. If you close the MPRIS applet and re-open it, it will now be correctly synchronized.

**Expected behavior**
MPRIS should immediately reflect any changes to playing state.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version 0.13.1

**Comment by jeffvli** [comment]
Thanks for reporting.

Fixed it for all the following cases:
- When using MPRIS controls (playerctl, etc.)
- From the tray
- From the main player controls
