### ISSUE TITLE
[BUG] Subsonic login api does not work

### ISSUE THREAD

**Issue by TLCFEM** [jeffvli/sonixd#253]
Please see the comments in #149 .

/rest/ping.view returns xml.

/rest/ping returns 404.

**Comment by jeffvli** [comment]
What server are you using?

**Comment by TLCFEM** [comment]
I am using the subsonic api shipped with the latest ampache. The test server can be found here. I am not sure if the configuration is correct. But the queries are as follows.

http://104.248.242.221/rest/ping.view?u=guest&p=guest&v=1.13&c=asd

```
<?xml version="1.0" encoding="UTF-8"?>
<subsonic-response xmlns="http://subsonic.org/restapi" status="ok" version="1.13.0"/>
```

http://104.248.242.221/rest/ping?u=guest&p=guest&v=1.13&c=asd

```
<!DOCTYPE HTML PUBLIC"-//IETF//DTD HTML 2.0//EN">
<html><head>
    <title>404 Not Found</title>
  </head><body>
    <h1>Not Found</h1>
    <p>The requested URL was not found on this server.</p>
    <hr>
    <address>Apache/2.4.52 (Debian) Server at 104.248.242.221 Port 80</address>
  </body></html>
```

**Comment by jeffvli** [comment]
Thanks, you're correct that it seems it doesn't work without the `.view` in the request URL (though all the other servers do work without it). I think I saw some comments in other discussions talking about using .htaccess to remove the `.view` dependency, but I can probably just refactor it on my side.

**Comment by TLCFEM** [comment]
Yes, this page https://github.com/ampache/ampache/wiki/API also mentions rewrite requests. It appears that `.view` is there, at least in the regex. Guess an if-else branch should be enough to cover both.

**Comment by jeffvli** [comment]
I packaged a dev build from #257 and uploaded it here: http://ftp.sonixd.com/%28%23253%29%20Sonixd-0.13.1-win.zip.

Can you try installing that version and check if there are any issues? You'll need to check the `Legacy Auth` checkbox when signing in.

**Comment by TLCFEM** [comment]
I compiled it locally and tested login and streaming, it is working smoothly. Thanks for the great project.

**Comment by jeffvli** [comment]
Great, thanks for confirming!
