### ISSUE TITLE
Add support to many languages?

### ISSUE THREAD

**Issue by hirusha-adi** [jeffvli/sonixd#260]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

Language support for everyone!

**Describe the solution you'd like**

Can create a script to automatically translate the key and put it to the value using google translate for many Languages, but it wont be 100% perfect for some languages...

**Comment by jeffvli** [comment]
I've been meaning to set up [weblate](https://weblate.org/en/) eventually. It has support for [machine translation](https://docs.weblate.org/en/latest/admin/machine.html) and manual translation.

**Comment by hirusha-adi** [comment]
that would be great. thank you
