### ISSUE TITLE
Metadata isn't updated when the song changes automatically

### ISSUE THREAD

**Issue by Luxed** [jeffvli/sonixd#263]
**Describe the bug**
When the song changes automatically, the metadata is not updated.

**To Reproduce**
- Go to the end of a song.
- Let it skip to the next song.
- Metadata about the song doesn't change until some kind of action is performed (i.e.: skip the song manually, play/pause, scrub forward)

**Expected behavior**
The metadata should be updated the song changes automatically.

**Screenshots**
![image](https://user-images.githubusercontent.com/10234894/158277346-1bf0b193-6569-4206-a1db-0e9c5aef5a3d.png)

**Desktop (please complete the following information):**
 - OS: Linux (OpenSUSE Tumbleweed)
 - Version: 0.14.0

**Additional context**
This was working fine in 0.13.1

**Comment by Luxed** [comment]
Of course, I click on submit and the issue doesn't happen.
But I have noticed that this time I got the notification about the song change.
When the issue happens I do not get the notification.
As additional information, I also tried with the notifications turned off and the issue still happened.

**Comment by xiaohuirong** [comment]
I meet the same issue.
- OS：Ubuntu21.10

**Comment by jeffvli** [comment]
I'll check to see what's happening. I think I made a few small changes to it in the last couple releases.

**Comment by jeffvli** [comment]
Sorry for leaving this forr so long. Should be fixed for next release.
