### ISSUE TITLE
Confusing Exit Behavior on macOS

### ISSUE THREAD

**Issue by tomatgithub0** [jeffvli/sonixd#264]
**Describe the bug**
Contrary to common macOS apps, the exit button on the windows terminates the playback(practically restarts the app) while using the quit option in the menu closes the window while meataining the playback. They are behaving in the excat opposite manner IMO.

**To Reproduce**
1. Turn on [exit to tray] in the configuration.
2. Use the close button[X] on the window the close the window.

**Expected behavior**
Window closes without interrupting the playback.

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: 10.13.6

**Additional context**

**Comment by jeffvli** [comment]
The macOS exit behavior was adjusted a couple months back by @zackslash to reflect the behavior you listed in #198.

I don't have a macOS device to test it myself, but @zackslash can you comment on whether or not you're experiencing the same exit issue here?

**Comment by zackslash** [comment]
Hey, I'm running macOS **10.15.7** on this machine.

I was not able to replicate this inconsistency between the two buttons; both the close button and quit from the menu result in the app fully quitting (no continuation of playback) as far as I can tell.

However, if setting 'Settings' > 'Other' > 'Windows' > 'Exit to Tray' is switched 'ON' then it is possible to click either 'close' or exit from tray and have the music continue playback while the app is closed but from what I can tell this is also consistent behaviour between the two buttons.

![Screenshot 2022-03-15 at 22 56 50](https://user-images.githubusercontent.com/2040617/158486136-b04b56e1-414e-40f6-854e-9f6df25c7438.png)

@tomatgithub0 please can you confirm what your 'Exit to Tray' value is set to?

I was considering making a PR with some default values for MacOS (such as the TitleBar Style) if the project is open to it, so it would be nice to get this resolved too.

**Comment by zackslash** [comment]
Hey,

I've been trying to dig into this a bit further.

The behaviour of these buttons is consistent for me after enabling 'exit to tray'.
Either quitting from the tray or the close button both result in the window closing and playback continuing.

@tomatgithub0 when you close the app (using the [X] button) does the app indicator (the black dot under the icon) dissapear from the tray?
![Screenshot 2022-03-15 at 23 24 06](https://user-images.githubusercontent.com/2040617/158488360-44f3de63-aa09-4a79-b6ab-d589ccd40950.png)

If you can provide some information on this it it may give some indication as to what is going on.

I have recently spotted an issue where the app cannot be closed but that is the opposite of this reported issue, I am considering making some PRs to both fix that and add some good MacOS defaults (such as TitleBar Style) if the project is open to it, so it would be nice to get this issue fixed too.

**Comment by tomatgithub0** [comment]
Hmm really strange, I just did a test again with [exit to tray] turned on, now it doesn't stop the music any more.

To answer your question, no, the indiator doesn't go away; in fact, it doesn't go away no matter what if you have [exit to tray] turned on, meaning there's no way to exit the app completely(Just like you mentioned). The only way is to turn off the option and quit the app.

The only reason I can think of is probably because it was a fresh install and the program hasn't fully initialized?

**Comment by tomatgithub0** [comment]
Correction: 

I just noticed that the problem actually happens when the [exit to tray] is turned off.

Sorry!

**Comment by zackslash** [comment]
Thanks for the update.

I agree that [exit to tray] set to ON should be the default for MacOS since it's more inline with native behaviour. I can also understand how when [exit to tray] is off it could be confusing.

I think the two points below are a fair summary of the issues here:

- [exit to tray] is 'off' by default
- When [exit to tray] is 'on' the exit button in the system bar does not quit the app.
