### ISSUE TITLE
Recently played section only updated when using the web client

### ISSUE THREAD

**Issue by arthurlutz** [jeffvli/sonixd#265]
**Describe the bug**
The recently played section in sonixd only contains tracks that I've listened to in the web client (with the same account), when playing via sonixd those tracks don't appear there. 

**To Reproduce**
1. Go to sonixd play track A
2. Go to jellyfin web client play track B
3. Go to sonixd, see only track B in the top section "Recently played"

**Expected behavior**
For recent tracks to be displayed no matter which client is used.

**Desktop (please complete the following information):**
 - OS: Ubuntu 
 -  Version 0.14.0

**Comment by jeffvli** [comment]
Did you enable the `scrobbling` setting in the Sonixd settings? That should properly update the recently played when listening to a track.

**Comment by SteveDinn** [comment]
Had this problem. Came here to log an issue. Turning on scrobbling solved the issue for me.
