### ISSUE TITLE
Playlist download

### ISSUE THREAD

**Issue by AnonEstranho** [jeffvli/sonixd#266]
Add a download button for playlists.

**Comment by jeffvli** [comment]
Added download options for playlists.
![image](https://user-images.githubusercontent.com/42182408/163098554-cb048fec-2345-4a74-8814-1ded02ebf828.png)

**Comment by AnonEstranho** [comment]
Thanks for implementing this feature, but I fear I was not specific about the enhancement. I was thinking on a download option similar to spotify, where if you don't have internet you can still listen in the client.
