### ISSUE TITLE
[BUG] [UI] White screen at login

### ISSUE THREAD

**Issue by TLCFEM** [jeffvli/sonixd#267]
To reproduce:

1. Start the application.
2. Without logging in, click gear (top right corner), click theme, white screen appears.

```
TypeError
Cannot read property 'children' of undefined
Call Stack
 findNodes
  renderer.dev.js:261714:74
 filterNodesOfTree
  renderer.dev.js:261734:10
 InputPicker.renderDropdownMenu
  renderer.dev.js:249328:92
 InputPicker.render
  renderer.dev.js:249525:21
 finishClassComponent
  renderer.dev.js:193858:31
 updateClassComponent
  renderer.dev.js:193808:24
 beginWork
  renderer.dev.js:195446:16
 HTMLUnknownElement.callCallback
  renderer.dev.js:180318:14
 Object.invokeGuardedCallbackDev
  renderer.dev.js:180367:16
 invokeGuardedCallback
  renderer.dev.js:180429:31
```

**Comment by jeffvli** [comment]
Does it brick the application even when restarting?

**Comment by TLCFEM** [comment]
Basiclly the whole UI becomes a white screen and users cannot do anything with it. Restarting the application gives the normal login tab. See screenshot.
![Screenshot from 2022-03-16 23-57-07](https://user-images.githubusercontent.com/19872523/158704830-ce682a63-eb65-4783-a591-59e6d2d902ee.png)
![Screenshot from 2022-03-16 23-58-08](https://user-images.githubusercontent.com/19872523/158704886-14957df9-2f6c-47e6-b40d-14347d0bc980.png)

**Comment by jeffvli** [comment]
I ended up removing the top action bar when on the login screen since most of those shouldn't be touched until after logging in.
