### ISSUE TITLE
Sorting Tracks on Favorites page lead to wrong song order

### ISSUE THREAD

**Issue by kleomedes** [jeffvli/sonixd#279]
**Describe the bug**
After changing the track's sort order on Favorites, the wrong song will be played if chosen manually from the list.

**To Reproduce**
1. Go to Favorites -> Tracks
2. Change the sort order (ex. by Artist)
3. Choose manually a song to play
4. Another song will be played

**Expected behavior**
Play the chosen song

**Desktop (please complete the following information):**
 - OS: Fedora 35
 - Version AppImage 0.14.0

**Comment by jeffvli** [comment]
Thanks for reporting this. Ended up fixing this interaction for other views as well:
- Favorites page
- Album page (single)
- Song list
