### ISSUE TITLE
App fonts should be local, not loaded from Google Fonts

### ISSUE THREAD

**Issue by poisonborz** [jeffvli/sonixd#284]
Problem:
Fonts for the app are loaded from Google Fonts. This might be kinda ok for websites, but bad ux for a desktop app for a number of reasons:
- What if there is no connection - the app displays broken UI when starting offline.
- There is no need for a cdn for a static resource used in a desktop app, unlike for a website
- Bad for privacy, Google will fingerprint each font load and the user's IP address...

Solution:
- Just provide the fonts from local sources.

**Comment by jeffvli** [comment]
Agreed, I'll have to address this.
