### ISSUE TITLE
Popup volume percentage on mouse over volume slider is now missing, only appears while changing volume

### ISSUE THREAD

**Issue by JingAr87** [jeffvli/sonixd#298]
Popup volume percentage on mouse over volume slider is now missing on 0.15.0, only appears while changing volume.

**Comment by jeffvli** [comment]
This was removed due to the slider changes which like you said appears when changing the volume.

What's your use case for the popup volume percentage? My thoughts are that adding another popup for the volume percentage would potentially clutter the display.

**Comment by JingAr87** [comment]
My library has lots of tracks with varying volumes, some get deafeningly loud at my usual playing volume and some extremely quiet. I usually mouse over to see the volume so I don't get my ears blasted. Although it is less of a problem now since the slider is logarithmic.

I don't see how it would clutter the display though, as it only appears when you mouse over the slider. I suppose you can make it a toggleable setting.

**Comment by jeffvli** [comment]
How about moving the hover to the volume icon. Does that work?

My issue is that the volume percentage would be duplicated while operating the slider.

![image](https://user-images.githubusercontent.com/42182408/164196106-22d94e4e-e8fc-4f9a-afa9-399018d92c2a.png)

**Comment by JingAr87** [comment]
Yeah, sounds good. Thanks for
