### ISSUE TITLE
apple m1 mac APP broken

### ISSUE THREAD

**Issue by GOWxx** [jeffvli/sonixd#301]
Download via https://github.com/jeffvli/sonixd/releases/download/v0.15.1/Sonixd-0.15.1-mac-arm64.dmg
install it, click APP in launch, show 
`"Sonixd" is damaged and cannot be opened. You should move it to the wastebasket.`
 - OS: [macOS Monterey version 12.3.1]
 - Version [0.15.1]

**Comment by jeffvli** [comment]
Can you try this fix? https://github.com/jeffvli/sonixd/issues/297#issuecomment-1099662436

**Comment by GOWxx** [comment]
> 

I tried this and it works, thanks.
```
sudo xattr -r -d com.apple.quarantine /Applications/Sonixd.app
```
