### ISSUE TITLE
[Navidrome] Playing an album does not get album into "recently played"

### ISSUE THREAD

**Issue by AndreCarvalho** [jeffvli/sonixd#303]
**Describe the bug**
Using Navidrome as media server, when playing an album, the album does not appear in "recently played" section (either in sonix and navidrome).

**Expected behavior**
The album should appear in "recently played" section

(Not sure if this is sonixd navidrome's fault, tbh.)

**Comment by copart** [comment]
Same here... this explains why my dynamic playlists in navidrome are not removing the played songs...

**Comment by jeffvli** [comment]
You need to enable the scrobbling under the player settings
![image](https://user-images.githubusercontent.com/42182408/164771321-979c0dd4-03e0-4159-95c0-3e89e0d8bafa.png)

**Comment by copart** [comment]
Just did that.... thank you!

**Comment by AndreCarvalho** [comment]
awesome! thanks @jeffvli
