### ISSUE TITLE
playing by folder

### ISSUE THREAD

**Issue by KarBoeh** [jeffvli/sonixd#309]
**Describe the bug**
If searching for album with "by folder"-feature and rightclicking on found album -> play the playlist won't be sorted correctly. Sorting only is by tracknumber, not using discnumber, if album consists of of more than one disc. Disc-tag is set correctly. playlist will first play all 1s, then 2s and so on. Which title-order is being used within one tracknumber seems to be random.
Albums consisting of more than one disc are -not- divided in several subfolders. Disk tag is set, filename starts with "disc#:1", followed by "track#:2"

**To Reproduce**
1. Go to 'folders'
2. search for album consisting of more than one disc 
3. right click on album
4. play
5. watch playlist order in miniplayer

**Expected behavior**
in this case Sonixd should use (and show) disc#-tag first and then sort by track# (within that disc#)
for example: (Disk - track)
1 - 1
1 - 2 
1 - 3
....
2 - 1
2 - 2
2 - 3
...

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: Win 11
 - Version 0.15.1

**Additional context**
Desired feature works as described above, if you go by "albums"

**Comment by jeffvli** [comment]
Sorry for the late response, but this should be fixed in the next version (0.15.3).
