### ISSUE TITLE
Remember window size

### ISSUE THREAD

**Issue by bwat47** [jeffvli/sonixd#31]
It would be great if when you resized (or maximized) the sonixd window, if it would remember that windows size (or maximize state if you had maximized it) the next time that you close/re-launch the program. 

currently, the program seems to always open with the same small window size (using Windows 10/11)

btw, thx for this great application!

**Comment by Elbullazul** [comment]
Sorry to revive an old issue, but the window doesn't remember its size in Windows currently (Windows 10 Home)

**Comment by ldexterldesign** [comment]
> The "remember window size" functionality was removed due to it breaking the installation a while back. It hasn't been resolved since. - https://github.com/jeffvli/sonixd/issues/130#issuecomment-1407545106

I suggest reopening this issue or creating a new issue to track it

Hope this helps

Regards
