### ISSUE TITLE
Tuna doesn't display cover or artist

### ISSUE THREAD

**Issue by Seb3thehacker** [jeffvli/sonixd#314]
**Describe the bug**
When using OBS local scrobbling the cover image nor the progress bar works.

**To Reproduce**
1. Enable local OBS scrobbling and configure OBS.
2. Play a song

**Expected behavior**
It should show a working progress bar along with the cover image.

**Desktop (please complete the following information):**
 - OS: Manjaro
 - Version 0.15.1

**Additional context**
I followed the Tuna setup video for Spotify exactly. The title shows properly but nothing else. Sonixd also doesn't generate a cover image in the file path set.

**Comment by jeffvli** [comment]
I don't have the bandwidth to troubleshoot the tuna integration at the moment, but someone was able to get it to work with zyphen https://github.com/jeffvli/sonixd/issues/136#issuecomment-1007969382.

**Comment by Seb3thehacker** [comment]
I tried his script but it didn't work for me so I created this script. It simply reads the URL in the image.txt file and downloads it to the desired location. You then just select put this script in your Sonixd dir with the other text files and add it in OBS. It works perfectly!

```
#!/usr/bin/env bash

while true; do
    wget -i /home/USER/DIR-SET-IN-SONIXD/image.txt -O cover.png
    sleep 1
done

```
