### ISSUE TITLE
JavaScript Error: Tried to write a message to a closed stream

### ISSUE THREAD

**Issue by Emaro** [jeffvli/sonixd#318]
**Describe the bug**
Every few minutes, a JavaScript error occures: *Tried to write a message to a closed stream.* (see screenshot). The playback contines fine, also after clicking OK.

Edit: If you don't click the error message away, the playback stops after a while. After clicking on OK, more of the same errors show up, but if you click all away, the playback resumes.

**To Reproduce**
1. Open Sonixd
2. Play music
3. Scrub or wait for the song to change and sometimes it happens randomly as well

**Expected behavior**
No JavaScript errors, more specifically no writes to closed streams.

**Screenshots**
![image](https://user-images.githubusercontent.com/25137789/168037990-2dd13986-0d66-4bb9-98df-a39d9692ef3b.png)

**Desktop (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS
 - Version: 0.15.1
 - Server: Subsonic API of the Nextcloud Music App v1.5.2

**Additional context**
Also, you may want to make the error message selectable, so users can copy + past it instead of capturing a screenshot. This would also allow to remove personal information more easily.

**Comment by Emaro** [comment]
This is probably related: https://github.com/dbusjs/mpris-service/issues/46

**Comment by michal4132** [comment]
It looks like "mpris:trackid" entry only allows letters and numbers. In my case [arg.id](https://github.com/jeffvli/sonixd/blob/main/src/main.dev.js#L254) contains something like "tr-991". Replacing ```arg.id``` with ```arg.id.replace('-','')``` fixes this error.
