### ISSUE TITLE
Option to edit tags as in Subsonic

### ISSUE THREAD

**Issue by octaviz** [jeffvli/sonixd#319]
**Is your feature request related to a problem? Please describe.**
An option to edit tags like in Subsonic would be nice

**Describe the solution you'd like**
A button with "Edit" inside the album

**Additional context**
More than a feature I guess it should be on the list of future developments that you surely have in mind. For everything else it is brutal, incredible and amazing how well this piece of App works on Mac, my library is more than 80,000 flacs, it handles it like nothing
<img width="1502" alt="feature-edit" src="https://user-images.githubusercontent.com/856579/168108106-881959f0-5c1f-4ab8-ad98-3fb18b43d293.png">

**Comment by jeffvli** [comment]
Would be a nice feature to have, but unfortunately Subsonic API does not allow us to edit the file tags.

**Comment by octaviz** [comment]
OK, Thx
