### ISSUE TITLE
Playback controls in taskbar thumbnail (Windows)

### ISSUE THREAD

**Issue by bwat47** [jeffvli/sonixd#32]
It would be nice if hovering over the sonixd taskbar icon showed playback controls (e.g. play/pause/next/previous)

See the below screenshot of foobar2000 for an example:

![image](https://user-images.githubusercontent.com/1442520/136983478-2998c7b0-63b9-4447-af67-6d07776d9f19.png)

**Comment by jeffvli** [comment]
Added for 0.3.0. Thanks for the suggestion!

![image](https://user-images.githubusercontent.com/42182408/137145765-8f70a64c-32f4-43f8-b840-5902177603f9.png)
