### ISSUE TITLE
mac-arm64 version does not open

### ISSUE THREAD

**Issue by cerspense** [jeffvli/sonixd#320]
Whenever I try to open the newest apple silicon build (Sonixd-0.15.1-mac-arm64.dmg), it says that "Sonixd" is damaged and can't be opened. I am on Monterrey 12.3.1 on an M1 Macbook air. The regular x64 mac version still works fine in Rosetta.

<img width="260" alt="Screen Shot 2022-05-19 at 1 53 25 PM" src="https://user-images.githubusercontent.com/25879200/169402729-00bda0f9-2669-4367-bbd0-906a759d7760.png">

**Comment by jeffvli** [comment]
Error is due to the binaries not being signed. Check #297 for the workaround.

**Comment by cerspense** [comment]
Ah I see now! It seems like it doesn't need to be rebuilt at all, luckily. Just running this works:
`sudo xattr -r -d com.apple.quarantine /Applications/Sonixd.app`
