### ISSUE TITLE
can't display normally in windows10

### ISSUE THREAD

**Issue by li-guohao** [jeffvli/sonixd#340]
**Describe the bug**
can't display normally in windows 10 , my version is 0.15.2

is sonixd use cdn? such as jsdelivr that can't access normally in china.

**To Reproduce**
need china network envirmonment, and then open this software by use windows10.

**Expected behavior**
loading....

**Screenshots**
![image](https://user-images.githubusercontent.com/46225881/174417203-9bd1cb29-33c5-4df0-9b4f-b12e3162cf0e.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Version 0.15.2

**Additional context**
I can't be sure if it's a cdn problem.

**Comment by li-guohao** [comment]
sonixd may need to support custom cdn URLs if it's cdn problem.

**Comment by jeffvli** [comment]
Sonixd is not using any CDN. It is connecting directly to the server that is specified when you login. If you use debugtron or build the app locally, you can check the browser devtools to see what errors you are getting.

**Comment by li-guohao** [comment]
> Sonixd is not using any CDN. It is connecting directly to the server that is specified when you login. If you use debugtron or build the app locally, you can check the browser devtools to see what errors you are getting.

thanks, i will add some information after try it on debug mode by the browser devtools.

**Comment by li-guohao** [comment]
current problem is old server info can't connect. it is normal after disconnect.  i close this issue. thank you.
