### ISSUE TITLE
Window not displaying in Windows 10?

### ISSUE THREAD

**Issue by Carter0108** [jeffvli/sonixd#341]
After a weekend away from my PC I have come back to find that Sonixd is no longer opening on my PC. Program appears on the taskbar and shows the preview window if I hover over it but the window will not open at all.

I have tried rebooting and reinstalling but neither has changed anything. Force closing and launching again also does nothing. Keyboard shortcuts to try and maximise the window also do nothing.

I don't know what exactly changed to produce this bug in the first place so I don't know how to reproduce it. Maybe a Windows update? Windows 10 build no. 19044.1766. Sonixd version is latest 0.15.2.

![Taskbar](https://user-images.githubusercontent.com/55948138/174497471-827970ed-526c-4b69-9d3f-f7cfe1c2c8d6.png)

Edit: Clearing the appdata got it working again but would be happy to provide any more information if possible to see if we can find out the cause of this?

**Comment by jeffvli** [comment]
Check this thread for a fix: https://github.com/jeffvli/sonixd/issues/278#issuecomment-1109775560

It's a bug with one of the settings.

**Comment by jeffvli** [comment]
Fixed in 0.15.3
