### ISSUE TITLE
Cannot update into existing directory (Win10)

### ISSUE THREAD

**Issue by GoTeamScotch** [jeffvli/sonixd#345]
**Describe the bug**
Upon opening Sonixd (v0.15.1) I was greeted with an update message. I went to Github and downloaded the new package (Sonixd-0.15.2-win-x64.exe). During the Installing phase, an error appears: "Sonixd cannot be closed. Please close it manually and click retry to continue". Sonixd is not running. I tried logging out and running the installer again to no avail. I also tried restarting my computer and that did not help either. Clicking cancel gives the message "Failed to uninstall old application files. Please try running the installer again.: 2". I also tried installing to Program Files (by choosing "anyone who uses this computer" when prompted as "who should this application be installed for?") and that yielded the same result. I then tried uninstalling Sonixd from my PC, and the uninstaller also got stuck at "Waiting for Sonixd to close".

**To Reproduce**
1. Open Sonixd version 0.15.1
2. Go to Github and download new version (0.15.2)
3. Close Sonixd
4. Run installer downloaded in step 2

**Expected behavior**
Version 0.15.2 would be installed in place of 0.15.1

**Screenshots**
![sonixd-install](https://user-images.githubusercontent.com/11036843/176277550-22b5cbb0-e572-4aa2-8f7f-a15898d333f0.png)
![sonixd-uninstall](https://user-images.githubusercontent.com/11036843/176277569-351130ee-8501-4cfc-99fe-138ab1eb96e8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 (64-bit)
 - Version: 21H2, build 19044.1766

**Additional context**
I tried running the installer for version 0.15.1 again to see what would happen, and it does not stop at this stage of the setup process. It complete the install process without issues.

**Comment by GoTeamScotch** [comment]
Update: I was able to get around the issue by deleting the Sonixd application folders in my AppData folder. I deleted them and then just ran the installer for v0.15.2. It installed just fine. Of course, I had to set Sonixd up again after upgrading, but at least it's upgraded now.

Probably safe to close this ticket now. I suppose if anyone else experiences this issue, this can be used for reference.

**Comment by GoTeamScotch** [comment]
Update- I experienced the bug again when trying to update to v 0.15.3 today.

![image](https://user-images.githubusercontent.com/11036843/179391997-f83bc27c-9d06-4756-835f-0edab13175a1.png)

I re-ran the installer with Process Monitor open and recorded the activity with it to see if there were any obvious symptoms (file not found errors, etc). I saw that the installer was trying to run "old-uninstaller.exe" from a temp folder. So, with the installer paused on the "Sonixd is running" error, I opened the temp folder where old-uninstaller.exe is located. I then ran old-uninstaller.exe as an administrator and the uninstaller opened and I was able to click through it to uninstall Sonixd. Once that was completed, I closed old-uninstaller.exe and returned to the main installer window and clicked Retry. This time, the installer was able to proceed and I am now using v0.15.3 successfully.

Must be a Windows permissions issue?

By the way, my install path is the default one chosen by Sonixd:
C:\Users\_{my windows username}_\AppData\Local\Programs\Sonixd
I also choose the "install only for me? option during setup.

**Comment by GoTeamScotch** [comment]
Update- problem persists when upgrading to 0.15.4

Same workaround still works. Again, seems to be a Windows permissions issue. Like the installer is trying to run old-uninstaller.exe as a non-privileged user or something.

1. Open the installer exe for the new version of Sonixd you're trying to update to.
2. Open windows file explorer. In the address bar, type %TEMP% and press enter. The address should refresh and be shown as "C:\Users\YourNameHere\AppData\Local\Temp".
4. Use the windows search box in the upper right to search for "old-uninstaller.exe". You should hopefully be shown the uninstaller app in the search results.
5. Right click on old-uninstaller.exe and click Open file location.
6. Copy everything in that folder to a different folder (make a new folder on your desktop and copy them all into there).
7. Run old-uninstaller.exe from its new location (on your desktop, etc).
8. old-uninstaller.exe will remove the old version of Sonixd.
9. Go back to the installer from step 1 and continue through installation.

With Feishin coming out soon, this might be a moot point. May not be worth fixing.

**Comment by piedoom** [comment]
Any idea how to uninstall this? I must be on an affected version. I tried deleting appdata as shown but am still running into it saying it is still running. Windows File Locksmith shows no processes using it.
