### ISSUE TITLE
In Filter, allow to set "is favorite" to true/false instead of only true

### ISSUE THREAD

**Issue by AndersMoberg** [jeffvli/sonixd#357]
I use the "starring" of albums as a notation for what albums are in my backlog to listen to. Thusly, it'd be nice to have the ability to **filter out starred albums** from the *Albums* view through filters.

![image](https://user-images.githubusercontent.com/4711748/178847654-b09a17ac-6d70-4eeb-b280-fc08ecbd1678.png)

But it only allows the user to set "Is favorite" to on/off. So the specific scenario I'd like isn't possible.

**Comment by jeffvli** [comment]
Added, will be in the next release.
