### ISSUE TITLE
Notification off by one?

### ISSUE THREAD

**Issue by kgarner7** [jeffvli/sonixd#362]
**Describe the bug**
I started to notice that recently, the system notifications for the current song are off by one. Specifically, with System Notifications enabled, if I let the player transition normally (I do not press forward/backward), the "now playing" song is the song that was previously playing, not the current one

**To Reproduce**
1. Start playing a song
2. Let the song finish, and let another song play
3. See the "now playing" notification show the prior song

**Expected behavior**
It should show the current song

**Screenshots**

https://user-images.githubusercontent.com/17521368/179893980-29e0c0ff-fa9b-4bb1-a884-d6085dd3eb2f.mp4

**Desktop (please complete the following information):**
 - OS: Arch (navidrome)
 - Version: 0.15.3

**Additional context**
I did some preliminary debugging, and it seems to be related to [Player.tsx](https://github.com/jeffvli/sonixd/blob/main/src/components/player/Player.tsx#L618). Specifically, I noticed that `playerNumber` did not match `playQueue.currentPlayer`, so it looks like the queue is referencing the old song? Not sure how that's happening...

**Comment by adamsih300u** [comment]
New user, noticed this too. Loving the app otherwise!
