### ISSUE TITLE
Not playing high bitrate M4A

### ISSUE THREAD

**Issue by Geksaedr** [jeffvli/sonixd#366]
Some high bitrate FLACs are not played. Most of 700+ kbps wont work but there are files around 900 kbps that are played for some reason.

Sonixd is on Win10 and connected to the Jellyfin server. Other apps work fine with those files.

Tried turning on and off the transcoding option but result is the same.

EDIT: Sorry it was M4A not FLAC

**Comment by jeffvli** [comment]
Are the FLAC files that don't work ALAC encoded by any chance? There's currently a limitation of the current player component in that it won't properly play transcoded files.

**Comment by Geksaedr** [comment]
Sorry, updated it. It was M4A not FLAC.

Is it possible to play ALAC files?

**Comment by jeffvli** [comment]
Unfortunately the web player component that Sonixd uses doesn't support transcoding from Jellyfin.
I don't have time to redo the implementation on the v.0.x.x version, but the [rewrite](https://github.com/jeffvli/sonixd-rewrite) will (and currently already does) support it.
