### ISSUE TITLE
Getting "Network Error" when attempting to login to server remotely through Cloudflare Tunnel.

### ISSUE THREAD

**Issue by GavinL2001** [jeffvli/sonixd#369]
I was able to connect to my navidrome server remotely when I didn't have it going through a tunnel, but ever since I switched, Sonixd has refused to connect. I can connect through a web browser and on my phone through play:Sub just fine. I have no rules set as to what kinds of devices can connect or the conditions they can connect in. Any help would be appreciated! Thanks!

**Comment by jeffvli** [comment]
I'm not familiar with how Cloudflare Tunnel works, but the way Authentication works should still be the same. You can check my comment here https://github.com/jeffvli/sonixd/issues/360#issuecomment-1188561759 for details on how the login works and what it's checking for.

As long as your server is returning the valid REST API response from the `/ping.view` endpoint, it should work.

**Comment by jeffvli** [comment]
Did you resolve your login issue? If so, what fixed it?

**Comment by GavinL2001** [comment]
I’m honestly not sure what fixed it, it just started working all of a sudden. Maybe it was because I was not home and it worked when I got home, but otherwise I don’t know. Wish I could help more, but I’m just glad it started working.
