### ISSUE TITLE
How to close debug window

### ISSUE THREAD

**Issue by maicss** [jeffvli/sonixd#372]
**Describe the bug**
Cannot close debug window

**To Reproduce**
1. Go to 'settings'
2. Click on 'Other'
3. Scroll down to 'bottom'
4. Click switch `show debug window`
5. Debug window shows

**Expected behavior**
Some where to close the debug window

**Screenshots**
![image](https://user-images.githubusercontent.com/9784767/183303052-c0528e7c-b233-4dae-847c-feb7b0c508c9.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [0.15.3]
 - Screen resolution: 1920* 1200
 - Download [Sonixd-0.15.3-win-x64.zip](https://github.com/jeffvli/sonixd/releases/download/v0.15.3/Sonixd-0.15.3-win-x64.zip) release

**Additional context**
Close app and reopen it, the window still there.

**Comment by jeffvli** [comment]
Click the checkbox at the top left of the debug window, it will allow you to click the toggle underneath it.

**Comment by maicss** [comment]
It  works, but not friendly at all.

**Comment by maicss** [comment]
Another:

I fixed it by click `Reset defaults`, close app and reopen it.

1. click `Config`
2. click `Look & Feel`

Got a white screen.

https://user-images.githubusercontent.com/9784767/183588814-9dd775df-6271-45ef-a046-9ce79e40802c.mp4

**Comment by jeffvli** [comment]
1. Close Sonixd
2. Go to `%appdata%/sonixd` in Windows explorer and delete the `settings.json` file. (Also C:\Users\<your user>\AppData\Roaming\Sonixd\`)
3. Reopen Sonixd

This should fix it

**Comment by maicss** [comment]
Thanks.
