### ISSUE TITLE
Sonixd won't launch in Windows 10

### ISSUE THREAD

**Issue by runkaiz** [jeffvli/sonixd#374]
**Describe the bug**
![image](https://user-images.githubusercontent.com/34772239/184556236-474cb18e-e2c6-4596-9693-8e8e3251ebba.png)
The app launched with an error and hung in the background. No window other than the error appears.

On a new installation, I tried reinstalling.

**To Reproduce**
1. Open sonixd

**Expected behavior**
The app should open

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by jeffvli** [comment]
I think you may need to install this [C++ redistributable package](https://www.microsoft.com/en-us/download/details.aspx?id=48145). The error is complaining about something related to NodeRT, which is a native windows module.

**Comment by runkaiz** [comment]
Oh my, it didn't even take longer than a day after switching out of Linux for me to encounter things like this, thanks for the tip!

**Comment by runkaiz** [comment]
For feature reference, the following link ended up fixing the issue, it seems like 2015 by itself doesn't work.
https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170
