### ISSUE TITLE
Can't get favourites to work

### ISSUE THREAD

**Issue by mantis64** [jeffvli/sonixd#377]
Hi, 

Thanks for making such a great player.  I'm having a small issue.  

I'm using on Windows 10 to connect to my local emby server.  The favourites that I have on emby do not show up on the favourites list, nor if I select a new favourite does it show up on the favourites list.  

Is this a bug or am I doing something wrong?

Many thanks

**Comment by mantis64** [comment]
So @jeffvli can you help with this or offer some advice please?

**Comment by jeffvli** [comment]
Seems like the Emby's API has diverged from Jellyfin..

From an initial test it seems like both favorites and playlists do not work properly.
I will add a new server type for Emby when I have time.

**Comment by mantis64** [comment]
Appreciate you coming back to me.  Great project, thank you for making it.

Look forward to your new releases.
