### ISSUE TITLE
Electron version unspported

### ISSUE THREAD

**Issue by jugendhacker** [jeffvli/sonixd#393]
**Describe the bug**
This app is currently running on electron13 which is unsupported since quite some time. Pleases upgrade it, as it burdens a significant security risk.

**To Reproduce**
1. Take a look at https://github.com/jeffvli/sonixd/blob/main/package.json#L215

**Expected behavior**
Have at least electron version 18 in there (as this is the oldest still supported electron version)

**Comment by Estebiu** [comment]
Electron 13 also results in blurry text on wayland on hidpi displays, as it defaults to xwayland.

**Comment by jugendhacker** [comment]
@Estebiu thanks for the input, also using such an old electron version makes it hard for distributions to package sonixd, as they usually try to only ship supported electron version.

**Comment by jeffvli** [comment]
Upgraded to electron 22 in #397

**Comment by eonpatapon** [comment]
Would it be possible to release `0.15.4` which supports electron 22 ?

**Comment by jeffvli** [comment]
@eonpatapon Yes, I'll push it shortly.

**Comment by jugendhacker** [comment]
Thanks @kgarner7 for the fix and @jeffvli for merging, now the AUR package works again with official Arch Linux Electron packages.
