### ISSUE TITLE
Navidrome Favourite/starred error

### ISSUE THREAD

**Issue by DOFfactory** [jeffvli/sonixd#411]
**Describe the bug**
Whenever I load an item from the Favourite/Starred list from a Navidrome server, I get the following error.

**To Reproduce**
1. Star a song that is playing
2. Go to favourites
3. Play the same song

**Expected behavior**
Sonixd should play a song from the Favourite list without issues

**Screenshots**
![image](https://user-images.githubusercontent.com/10846169/206854993-d4485d78-0102-49b7-8595-a49dc2775de9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.15.3 

**Additional context**
N/A

**Comment by DOFfactory** [comment]
I think by mistake I found the potential culprit: 

![image](https://user-images.githubusercontent.com/10846169/207611677-9b7e450f-31c4-4d38-989f-11dbe17b677d.png)

If I click on the track list in this view to the artist (in red), I get the aforementioned error. If I click on the song title (green), the playback starts correctly. I think this is a bug.

**Comment by jeffvli** [comment]
Fixed in 0.15.4.
