### ISSUE TITLE
Navidrome not recognizing sonixd as player, not scrobbling

### ISSUE THREAD

**Issue by jsspen** [jeffvli/sonixd#420]
Using the latest x86_64 AppImage on Linux Mint Mate 21.1
Connected to local Navidrome server, all appears well but not scrobbling
Looking at Navidrome's "Players" list I'm not seeing the instance recognized, which would explain no scrobbling
Other clients (Android app, Android web, Windows web Chrome, Linux web Firefox) are all properly reflected
Refreshing, disconnecting, and restarting both Sonixd and the Navidrome server does not result in any changes

**Comment by jeffvli** [comment]
Can you check that the username you've logged in on in Sonixd is the same case as your username in navidrome?

For example, if your username in navidrome is `USERNAME`, then you should log in as `USERNAME`, and not `Username`. 
This also happened in #400. If it still does not resolve, check your Navidrome server logs to see if anything shows up there.

**Comment by jsspen** [comment]
@jeffvli that was it! Thanks, all working now.
