### ISSUE TITLE
As a user I want a `Plays` column in each list view so I can more easily start playback from where I previously stopped #ENHANCEMENT #SUGGESTION

### ISSUE THREAD

**Issue by ldexterldesign** [jeffvli/sonixd#424]
👋

Thanks for wonderful software

**Is your feature request related to a problem? Please describe.**

As a user I want a `Plays` column in each list view so I can more easily start playback from where I previously stopped (primary use case is resuming an album or playlist)

**Describe the solution you'd like**
A `Plays` column is usually what I rely on in other players

**Describe alternatives you've considered**
For the time being I'm having to kludge this with the `Fav` feature but not ideal!

If you're reading and:
- agree then please vote up (e.g. +1, like), or;
- disagree then please vote down (e.g. -1, dislike) - I'd love to know why?

If there's a way of currently solving this use case without adding a new feature then I'm all ears 👂..?

Welcome feedback/input

Hope this helps

Sincerely

**Comment by ldexterldesign** [comment]
Aside, how is your repo' automatically adding labels (i.e. `enhancement`)?

**Comment by jeffvli** [comment]
A `Play count` column already exists on all list views that support it.

![image](https://user-images.githubusercontent.com/42182408/221811554-fbfa8373-3df9-4522-aa2a-48eb09a79002.png)

> Aside, how is your repo' automatically adding labels (i.e. enhancement) 🧐?

Labels can automatically be added based on the github issue template.
https://github.com/jeffvli/sonixd/blob/b298fe47887255c4723c4399e675fb1ae1c39503/.github/ISSUE_TEMPLATE/feature_request.md?plain=1#L5

**Comment by ldexterldesign** [comment]
Thanks for reply

I've now discovered there's no Favourites list view because the Favourites is divided into Tracks, Albums and Artists; and these views inherit the list view column settings respectively - makes sense 🤦:

<img width="1840" alt="Screenshot 2023-02-28 at 16 15 41" src="https://user-images.githubusercontent.com/1715809/221912657-ae2abdc5-41a9-4eb8-929b-1871d982490a.png">
<img width="1840" alt="Screenshot 2023-02-28 at 16 14 55" src="https://user-images.githubusercontent.com/1715809/221912686-c6aa83dc-a342-496d-9684-5206f2be106b.png">
<img width="1840" alt="Screenshot 2023-02-28 at 16 15 21" src="https://user-images.githubusercontent.com/1715809/221912708-a2115e15-63d2-49b9-8fa3-b1ccf32c3a5d.png">

Aside, is there a reason both the terms "songs" and "tracks" exist in this context? If these terms were/are the same thing then I may have grokked this issue earlier. If you agree then perhaps it's something that could be remedied app-wide as I see both terms sprinkled throughout..?

Cheers
