### ISSUE TITLE
Making Media Controls work on Mac OS X Ventura

### ISSUE THREAD

**Issue by zeknoss** [jeffvli/sonixd#425]
Since this is going to be a helpful reference for those who struggle with making SonixD work with media keys, here's what you have to do:

1. Launch Settings
2. Go to Privacy & Security > Media & Apple Music
3. Add SonixD to the list of applications that can access to media activity

Now you should be able to use your media controls to control SonixD.

Also you could install NoTunes via brew to prevent iTunes from launching automatically each time you press a media hotkey.

Cheers!

![image](https://user-images.githubusercontent.com/2834599/219645199-e2fcc82b-9f43-46d5-b72b-0821049efe57.png)

**Comment by ldexterldesign** [comment]
[Duplicate]

Please check existing before creating new

[]Duplicate]: https://github.com/jeffvli/sonixd/issues/376

**Comment by zeknoss** [comment]
> [Duplicate](https://github.com/jeffvli/sonixd/issues/376)
> 
> Appreciate tip but please consider existing issues before creating something new - your submission would have had greater impact there
> 
> Regards

I first searched for a thread that you mentioned however it seems I missed it. Otherwise I would have written over there instead.

Thanks

**Comment by ldexterldesign** [comment]
Please help the project owner by closing this issue

Cheers
