### ISSUE TITLE
0.15.4 broke minimizing to try on Windows

### ISSUE THREAD

**Issue by JVT038** [jeffvli/sonixd#430]
**Describe the bug**
When using the latest 0.15.4, Sonixd will quit when closing the window. This immediately stops playback and the icon isn't shown in the taskbar.
I uninstalled Sonixd and installed 0.15.3 and the 0.15.3 version does properly exit to tray. So it's clearly a 0.15.4 issue.

**To Reproduce**
1. Go to Sonixd.
2. Click on a song to start playback.
3. Close the Sonixd window.

**Expected behavior**
I expected Sonixd to continue playing and exit to tray like usual

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.15.4

**Comment by IceWreck** [comment]
On Linux too. 
Pinging @jeffvli

**Comment by jeffvli** [comment]
Thanks for reporting. I took a quick look and can only confirm that `Exit to tray` is broken.
`Minimize to tray` is still working as expected.
