### ISSUE TITLE
Editing a playlist wipes (nearly) all tracks from the playlist under Navidrome server

### ISSUE THREAD

**Issue by telekineticyeti** [jeffvli/sonixd#437]
**Describe the bug**
I am using Navidrome 0.49.3 (8b93962f). Adding tracks to a playlist works mostly as intended, however if you open the playlist in Sonixd and attempt to move or remove tracks, the playlist save will fail and remove almost all tracks from the playlist. This seems to only happen in playlists with around 200 or more tracks.

**To Reproduce**
1. Create a playlist, add 202 or more tracks to it.
2. Navigate to the playlist and reorder a single track or remove a single track
3. Click 'Save' icon
4. Toast popup appears with the message 'Errored while saving playlist'
5. Click 'Save' again to retry
6. Toast popup appears with the message 'Recovered playlist from backup'
7. The playlist is almost entirely wiped of all tracks. Sometimes there are a few tracks, but never more than 100.

**Expected behavior**
Editing tracks in an existing playlist should not remove unrelated tracks from the playlist.

**Screenshots**

The playlist being edited with 202 tracks:
<img width="1213" alt="image" src="https://github.com/jeffvli/sonixd/assets/2192465/2db963a2-2761-45a6-8b75-a3ae39c08a51">

First toast message recieved when removing a single track and clicking save:
<img width="712" alt="image" src="https://github.com/jeffvli/sonixd/assets/2192465/b2be2c91-981b-4026-bff1-b9183b6cff1d">

Second toast message recieved when trying to save again:
<img width="521" alt="image" src="https://github.com/jeffvli/sonixd/assets/2192465/9ee145a0-831a-4fb5-aaab-fd4af3d1df30">

The playlist state after the second save attempt. All tracks removed (see header), but some still visible in the playlist grid. These dissapear when navigating away from the playlist and returning to it again:
<img width="1205" alt="image" src="https://github.com/jeffvli/sonixd/assets/2192465/59c00456-dd77-43eb-8769-367c8c1cee87">

**Desktop (please complete the following information):**
 - OS: Windows and OSX
 - Version 0.15.5

**Additional context**
I suspect there is some kind of pagination of the API request happening here on Navidrome's part, however I'm not able to confirm this. I had another playlist with 355 tracks that was reduced to 55 tracks when reproducing this defect on it. The 55 tracks that remained were the last 55 tracks at the bottom of the playlist.

It's probably worth noting that attempting to add greater than 100 tracks to a playlist at once tends to fail, despite a toast message indicating that the operation succeeded. However, this is probably worth submitting as a seperate bug as the behaviour is not as detrimental as this one.

**Comment by jeffvli** [comment]
I'm unable to reproduce this on my side.
Are you accessing your Navidrome instance through a reverse proxy?

**Comment by telekineticyeti** [comment]
Yes, I am using a reverse proxy - I'll give it a go without the proxy and see what happens

**Comment by jeffvli** [comment]
My educated guses is that you may be running into a HTTP 414 error (URI too long) when trying to save. Sonixd re-creates the playlist when reordering tracks in the playlist, which appends each songId into the url query string. Navidrome uses UUID's for ids (e.g. `7ec3634094e7594670ec27eb6362a5ba`) which are quite long, so any time you save a playlist, it creates a fairly long query string which is sent to the API.

If this is the case, you may need to update your reverse proxy configuration. [Nginx as an example](https://stackoverflow.com/questions/1067334/how-to-set-the-allowed-url-length-for-a-nginx-request-error-code-414-uri-too)

**Comment by telekineticyeti** [comment]
I can confirm that with the proxy taken out of the equation, the defect doesn't occur and Sonixd functions as expected. Thanks for the insight! I'll close this issue.
