### ISSUE TITLE
Fullscreen App Display

### ISSUE THREAD

**Issue by FaboThePlayer** [jeffvli/sonixd#438]
Hi, it would be awesome to add fullscreen app display, like that one from Spicetify plugin named "Full App Display". It shows cover, title and controls on the big screen.

**Comment by Gecked-Deck** [comment]
There's a fullscreen mode in Feishin, if you wanted to try that out. Not exactly the same, but I think it's pretty similar to what you're describing.
![image](https://github.com/jeffvli/sonixd/assets/104325921/1cf216c8-35f0-429a-a749-a7796c4bc390)

**Comment by FaboThePlayer** [comment]
Thanks! I already downloaded Feishin and considering changing to that app.

**Comment by Gecked-Deck** [comment]
No problem, just an FYI because I don't believe it's super clear on how to use it, you have to click on the expanded album art to use this mode.
