### ISSUE TITLE
Minimize to Tray Option

### ISSUE THREAD

**Issue by ncarmic4** [jeffvli/sonixd#45]
**Is your feature request related to a problem? Please describe.**
This request is mainly for windows but could also apply to some linux distros. I'm used to spotify, being able to click exit but not really exit and continue playback with the window minimized to the tray.

**Describe the solution you'd like**
* Toggle options that allow you to "close to tray on exit" or "close to tray on minimize"
* Tray menu can be right clicked to open a menu on the tray icon
* Tray menu can be single or double clicked to restore full window

**Describe alternatives you've considered**
None

**Additional context**
I can attempt to implement this eventually if you don't get around to it. By the way, I cloned and liked what I saw on your dev branch 🙂

**Comment by jacktheripper19** [comment]
Hello, thanks for working on this feature. I wanted to point out that sonixd doesn't show up in the tray for kde plasma even though it still plays in the background when closing.

**Comment by jeffvli** [comment]
@jacktheripper19 A fix is implemented in #150 by @gelaechter
