### ISSUE TITLE
Shuffle through whole Music Server

### ISSUE THREAD

**Issue by Mammutor** [jeffvli/sonixd#46]
Hello my friend,
first of all thank you for your nice client!
I wish to hear all of my music in my library, but there is not an option to do this. So I think that you can do in the left a "Radio" button or something like that. That would be wonderful.

Have a nice day

Greetings
Mammutor

**Comment by jeffvli** [comment]
Hi, there's currently a way to shuffle random songs from your library if you use the `Add random` button on the `Now Playing` page. I'm not sure if this is what you're asking for, but if not can you clarify the feature a little more for me?

![image](https://user-images.githubusercontent.com/42182408/137640403-7322f17d-3ce0-4bfe-bd75-923962f54cba.png)

**Comment by soyelmismo** [comment]
Yes. this should have its own category or section cuz its very hidden and its commonly used... i was searching this for days and now i needed to join github issues to find it... thanks


it should be in a songs section like albums but for separated songs, and the random play in that place
