### ISSUE TITLE
Track/Song right-click menu not working in modal view

### ISSUE THREAD

**Issue by pawelmalak** [jeffvli/sonixd#55]
**Describe the bug**.
If album is displayed in modal view, right clicking on track displays menu with actions under the modal, making it impossible to perform an action on a song like adding it to the queue.

**To Reproduce**
1. On Album, click "View in modal"
2. Right click on any track

**Expected behavior**
Menu with options to be displayed on top.

**Platform**
 - OS: Windows
 - Version 0.3.0

**Screenshots**

![app](https://user-images.githubusercontent.com/24780509/138782907-507ea604-e0e8-4aa5-b38b-b2877638eb53.png)

**Comment by jeffvli** [comment]
`Add to playlist` popover is being blocked by modal in 0.5.0.
