### ISSUE TITLE
folder view is blank

### ISSUE THREAD

**Issue by dln949** [jeffvli/sonixd#69]
sonixd 0.4.1 appimage on Ubuntu Bionic.  

In the folder view, no information is given, see the attached screenshot. 
![Screenshot from 2021-11-05 00-22-48](https://user-images.githubusercontent.com/8601150/140462463-3232ec61-4c27-4c2e-8b67-6d2ba02c990e.png)

**Comment by jeffvli** [comment]
There's a bug in 0.4.1 where the `Title` column is blank. If you use the `Title (Combined)` column it will show the titles.

It's already fixed and slated for 0.5.0.
