### ISSUE TITLE
Adding and removing songs to and from playlist is not reliable

### ISSUE THREAD

**Issue by dln949** [jeffvli/sonixd#70]
Sonixd 0.4.1 appimage, ubuntu Bionic

Adding songs to a playlist:  

I have a genre of songs called "Blues".  In the genre view in sonixd, I see "Blues" in the list of genres, it shows about 360 tracks.  I expand the "Blues" genre category, and then select all entries, then right click and choose "Add to playlist", and I select the existing (empty) playlist of "Blues".  Sonixd then responds with a message that it added 876 tracks.  When I look in the "Blues" playlist, I see all those songs in the blues genre; and, I see what looks to be a random selection of roughly 500 additional tracks.  

Removing songs from a playlist:  

Continuing the above scenario:  I sort the playlist by genre.  Then, I select all tracks that are NOT of the blues genre.  Then I right click and choose "Remove selected".  But, sadly nothing happens, they remain.  

Why did my attempted method of adding songs to a playlist not work?  

Why did my attempted method of removing songs from a playlist do nothing?

**Comment by jeffvli** [comment]
![image](https://user-images.githubusercontent.com/42182408/140512402-8b8e32ed-b0f9-43fb-9916-9f4f21bec5e3.png)

Playlists are never modified on the server until the `Save` button is pressed, so press that button after making changes.

I'm not sure about the extra 500 random tracks as I'm currently unable to reproduce it, but there's also a bug in 0.4.1 where you can't fully delete all songs in a playlist (needs at least 1 track).

**Comment by deluan** [comment]
> needs at least 1 track in **Navidrome** only

Fixed and will work as expected in the next release ;)

**Comment by dln949** [comment]
> > needs at least 1 track in **Navidrome** only
> 
> Fixed and will work as expected in the next release ;)

Thanks.
