### ISSUE TITLE
Feature Request: Media Keys Control

### ISSUE THREAD

**Issue by Typhonragewind** [jeffvli/sonixd#79]
I'm loving using this, the interface feels so snappy.

Just a minor feature request, if you ever feel bored. Not super important.

Add support to control playback through keyboard media keys (such as play, next, previous, volume control, etc)

**Comment by jeffvli** [comment]
The following media keys are already supported:
- `PlayPause`
- `Next`
- `Previous`
- `Stop`

There's also a toggle in the config under `Player` to enable the media keys globally which has been tested on Windows and Linux (Linux uses the MPRIS interface). For macOS, you'll have to add Sonixd as a [trusted accessibility client](https://developer.apple.com/library/archive/documentation/Accessibility/Conceptual/AccessibilityMacOSX/OSXAXTestingApps.html) for the media keys to work. I haven't personally tested this as I don't have a macOS device, but it is listed in the [Electron docs](https://www.electronjs.org/docs/latest/api/global-shortcut#globalshortcutregisteraccelerator-callback).

**Comment by Typhonragewind** [comment]
Doh, didn't think to look for that in the options, my bad

**Comment by JVT038** [comment]
> The following media keys are already supported:
> 
>     * `PlayPause`
> 
>     * `Next`
> 
>     * `Previous`
> 
>     * `Stop`
> 
> 
> There's also a toggle in the config under `Player` to enable the media keys globally which has been tested on Windows and Linux (Linux uses the MPRIS interface). For macOS, you'll have to add Sonixd as a [trusted accessibility client](https://developer.apple.com/library/archive/documentation/Accessibility/Conceptual/AccessibilityMacOSX/OSXAXTestingApps.html) for the media keys to work. I haven't personally tested this as I don't have a macOS device, but it is listed in the [Electron docs](https://www.electronjs.org/docs/latest/api/global-shortcut#globalshortcutregisteraccelerator-callback).
> 
> I can possibly add the `VolumeUp`, `VolumeDown`, and `VolumeMute` media keys since it does seem like [Electron supports it](https://www.electronjs.org/docs/latest/api/accelerator/#available-key-codes).

Does this work?
It doesn't work for me. 
I'm using Windows 10, and when I press pause / resume, it doesn't do anything.
Additionally, when changing the volume, it doesn't show the currently played song with playback controls.
For example, when I play a YouTube video:
![image](https://user-images.githubusercontent.com/47184046/146653687-5a0afe04-5cd8-4b0a-b9d3-baeb740f67c7.png)
It only just shows the volume control bar. 
I would like it if you'd add support for this.

**Comment by jeffvli** [comment]
@JVT038 If you look at the available key codes, the only ones that are supported are:
![image](https://user-images.githubusercontent.com/42182408/146690065-e491a777-8b01-4df2-8ed3-dbb656418502.png)

I don't see separate ones specifically for `pause` or `resume`, and is usually combined as the Play/Pause key. Do you have a special keyboard that has those specific media keys? If those are separate, you could possibly rebind them using AutoHotkey to the media keys that Electron supports.

I can look into adding the Windows playback controls though.

**Comment by jeffvli** [comment]
Reference for multimedia controls: https://stackoverflow.com/questions/49348298/how-to-use-systemmediatransportcontrols-with-electron
