### ISSUE TITLE
Cannot play any audio from Navidrome server

### ISSUE THREAD

**Issue by marcinbinczyk** [jeffvli/sonixd#81]
**Describe the bug**
Cannot start playing any audio. Playhead is stuck at 0:00.

**To Reproduce**
1. Launch application
2. Click Play button on any item from library

**Expected behavior**
Music starts after hitting play on album/track.

**Screenshots**
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/2116558/141431887-69b8a336-3081-463e-a36e-0c08b28d5cc5.png">

**Desktop (please complete the following information):**
 - OS: tested on Windows 11 / macOS 12.0.1
 - Version 0.6.0

**Additional context**
Connecting to Navidrome server version 0.46.0.
All music on server is in ALAC format.

**Comment by jeffvli** [comment]
Unfortunately browsers don't support ALAC format (Sonixd runs off of Chromium Electron). You'll have to either convert your files or force the Sonixd player in your Navidrome UI to to transcode your files in the settings (https://github.com/navidrome/navidrome/issues/1441).

1. Go to the settings dropdown in the Navidrome UI
2. Open the `Players` settings
3. Click on the `sonixd` player
4. Select a transcoding profile for the player and save

![image](https://user-images.githubusercontent.com/42182408/141437487-c9c959fa-0860-4008-b6ad-71ce0c06f633.png)


![image](https://user-images.githubusercontent.com/42182408/141437516-7c77ceea-bdf2-4097-a36e-de25eee1db82.png)

**Comment by marcinbinczyk** [comment]
Ok, that worked! Thank you!
