### ISSUE TITLE
Media keys suppport

### ISSUE THREAD

**Issue by hscells** [jeffvli/sonixd#82]
**Is your feature request related to a problem? Please describe.**
The problem is that I would like to use the media keys (i.e., play/pause, next/prev) on my laptop (mac) to control sonixd.

**Additional context**
For the longest time until I stopped subscribing to google music, I used to use this (electron) app: https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-

It has support for media keys, so it might be a useful reference?

**Comment by jeffvli** [comment]
Can you try adding Sonixd as a [trusted accessibility client](https://help.rescuetime.com/article/59-how-do-i-enable-accessibility-permissions-on-mac-osx)? This is noted in the [Electron docs](https://www.electronjs.org/docs/latest/api/global-shortcut#globalshortcutregisteraccelerator-callback) which I also have noted in the [faq](https://github.com/jeffvli/sonixd/discussions/15). You'll probably also have to tick the "Enable global media keys" checkbox in the player settings.

I don't have a mac so I've never tested it, but if you can confirm this for me I can add a notice inside the client itself.

**Comment by hscells** [comment]
These steps did indeed resolve the problem. Thanks!

To be honest, I missed this link to your great FAQ page in the Readme. May I suggest to make this link more prominent?
