### ISSUE TITLE
macOS title bar visual bug

### ISSUE THREAD

**Issue by hscells** [jeffvli/sonixd#83]
**Describe the bug**
macOS titlebar is not visually correct. (#23)

**To Reproduce**
Change titlebar to macOS

**Screenshots**
See below. Window in front is Finder, window behind is sonixd.

![Screen Shot 2021-11-15 at 9 10 32 am](https://user-images.githubusercontent.com/6388537/141702486-1642afd6-7e72-4245-a255-112ef7045355.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.14.5

**Comment by jeffvli** [comment]
Thanks for the comparison pic, I'll try to match the sizing.

**Comment by hscells** [comment]
Okay, cool, thanks. I'd be happy to test it out for you to get it looking correct.

**Comment by jeffvli** [comment]
I did a bit of tweaking to better match the original:

![image](https://user-images.githubusercontent.com/42182408/141708019-b775d378-d9ac-4c19-a449-615e459d8788.png)

Overlaying them seems to indicate the button sizes and spacing are correct:
![image](https://user-images.githubusercontent.com/42182408/141708235-2fd3eaa1-6818-4a19-b167-7a45d40caf9a.png)

The changes are currently on my [dev](https://github.com/jeffvli/sonixd/tree/dev) branch if you would like to test and review it.
