### ISSUE TITLE
Javascript error when resizing window

### ISSUE THREAD

**Issue by hscells** [jeffvli/sonixd#84]
**Describe the bug**
A Javascript exception occurs when I resize the window.

**To Reproduce**
Grab a corner of the sonixd window and drag it.

**Expected behavior**
No Javascript exception should appear.

**Screenshots**

![Screen Shot 2021-11-15 at 9 13 33 am](https://user-images.githubusercontent.com/6388537/141702552-01226478-4075-4cad-8848-aa8971d0ebd4.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.14.5

**Comment by jeffvli** [comment]
Thanks, accidentally introduced this bug in the latest release. It'll be resolved in 0.7.0.
