### ISSUE TITLE
Multiselect & Rating: Rate multiple songs at once

### ISSUE THREAD

**Issue by WolfgangDpunkt** [jeffvli/sonixd#95]
**Describe the solution you'd like**
I would love to be able to select multiple songs and then give them all the same 1-5 star rating (⭐⭐⭐⭐⭐) at the same time.
In short: 
Select multiple songs, context menu: Rate with 1-5 stars.

Background: I have used Musicbee for years to rate my music collection finely differentiated with the 5-star system. The Subsonic ecosystem does not read/support those ratings. 
Now I'm looking for a way to rate a whole bunch of songs at once (which I've, for example, compiled via playlists based on the previous rating). I want to transfer, so to speak, that other rating system (from Musicbee) semi-automatically into a Subsonic-compatible 5-star rating.
 
But that is not possible in Navidrome or Sonixd. Since web UIs like the Navidrome-one can't handle that many songs at once very well, it would be best if Sonixd supported that.

**Describe alternatives you've considered**
I have tried a lot of other web and desktop music players and music managers. None offer this functionality. Many have abandoned the star rating system altogether. Sonixd is even the first I've seen to support the Subsonic API and 5-star ratings at the same time and really working. So this is where I put all my hopes.
 
**Additional context**
A great app that can fill a painful gap especially on macOS. Thanks a lot!

**Comment by jeffvli** [comment]
I've been kind of putting off additional functionality for the ratings since I don't personally use them, but this is definitely doable. I'll add this onto my roadmap for the next release.

**Comment by WolfgangDpunkt** [comment]
That's extraordinarily friendly, thank you very much and have a nice weekend.

**Comment by jeffvli** [comment]
![image](https://user-images.githubusercontent.com/42182408/143012412-7aab13d6-cbed-4ff0-8b3f-2ff5962bb4ea.png)

I added a context menu option to bulk set ratings for songs, albums, and artists.
There's currently no way to view artist/album ratings from Sonixd though as Navidrome's API does not return the values.

I've put in a separate request (https://github.com/navidrome/navidrome/issues/1486) for that, so if it's added then you'll be able to view them.
