### ISSUE TITLE
[Feature Request] 5-star rating system

### ISSUE THREAD

**Issue by quietmansoath** [jeffvli/sonixd#97]
I see that the project has navidrome tagged in the description. Navidrome currently supports rating songs on a five-star scale, which is not apparent in the features from the screenshots. Please consider bringing that functionality over! That and smart playlists, but this one will likely have to wait.

**Comment by jeffvli** [comment]
Ratings (for songs) are already supported when enabling the `Rating` column in the list-view settings. I have an item on my roadmap (#95) to add support to rate multiple songs at once

![image](https://user-images.githubusercontent.com/42182408/142796491-d91ac052-69f3-468a-abfa-685306be024b.png)

As for smart playlists, those should already be supported, as Navidrome smart playlists are created on the server-side, and show up alongside existing playlists.

**Comment by jeffvli** [comment]
Closing this in favor of #95.
